import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const srv = spawn('python3', ['-m', 'http.server', '8445', '--bind', '127.0.0.1'], { cwd: '..', stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 800));
const browser = await chromium.launch();
const page = await browser.newPage();
const warns = [];
page.on('console', (m) => { if (m.type() === 'warning' || m.type() === 'error') warns.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', (e) => warns.push('PAGEERROR: ' + String(e)));
await page.goto('http://127.0.0.1:8445/index.html', { waitUntil: 'load', timeout: 60000 });
await page.waitForFunction(() => !!window.__clock, null, { timeout: 60000 }).catch(() => warns.push('NO __clock'));
await new Promise((r) => setTimeout(r, 1500));
console.log(warns.length ? warns.join('\n') : 'BOOT SILENT');
await browser.close();
srv.kill();
