// §88 — favicon.svg, generated from the REAL house mark.
//
//   node --import ./tools/three-node-loader.mjs tools/make-favicon.mjs
//
// The mark is §41's WS monogram on the winding crown's face: four stroked W
// limbs and two annular-sector S bowls, with the stroke width DERIVED (2 x the
// proud relief height) and the bowl radius SOLVED so the two bowls meet
// tangentially. None of that is redrawn here. This imports
// `brandMarkShapes` from src/geometry.js and renders the shapes it returns —
// the same call the crown mesh extrudes — so the icon cannot drift from the
// part. Change the monogram and re-run this; there is nothing to keep in step
// by hand.
//
// WHY A GENERATED FILE IS COMMITTED rather than built at deploy time. The
// deploys are dependency-free by design: tools/ never ships and the payload is
// static files. A favicon that needed the build step would be the first asset
// that did. So the SVG is committed, carries a header naming the tool that
// wrote it, and is regenerated by re-running this.
//
// The two figures that are NOT the mark's:
//   - the ground is #0b0d10, the page background index.html and the manifest
//     already declare, so the icon sits on the app's own colour rather than a
//     new one;
//   - the ink is #d6d9dd, MATS.steel's `color` in src/materials.js — the
//     material the crown's mark is actually made of. A flat fill cannot be a
//     metal, but it can at least be the right metal's albedo.
//
// SAMPLING. The bowls are true arcs. ExtrudeGeometry samples them at
// curveSegments = 10 because that is a sensible triangle budget on a part a
// few millimetres wide; an icon has no such budget, so they are sampled at
// ARC_DIVISIONS below. Same curve, finer — not a different shape.
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { chromium } from 'playwright';
import { brandMarkShapes, makeCrown } from '../src/geometry.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ARC_DIVISIONS = 96;

// THE MARK IS SIZED BY BUILDING THE ACTUAL CROWN, not by quoting its numbers.
// The first cut of this file guessed capTopR as a ratio of bodyR; it is
// bodyR - CAP_DROP, a subtraction, so the mark came out two thirds of its real
// size and §41's legibility assert fired on the way past — the S bowls would
// have filled into blobs. That assert is the reason this now asks the part.
//
// bodyR/bodyH are the winding crown's from src/main.js. capR comes off the
// built group's own userData; tubeR and markR then follow makeCrown's two
// documented relations. The result is CHECKED against the mark the crown
// actually carries, so this cannot drift back out of step silently.
const BODY_R = 5.425, BODY_H = 4.55;         // src/main.js — the winding crown
const crown = makeCrown({ bodyR: BODY_R, bodyH: BODY_H });
const capR = crown.userData.crown.capR;      // = bodyR - CAP_DROP
const TUBE_R = BODY_R * 0.085;               // makeCrown: the mark's relief tube
const MARK_R = capR - 2 * TUBE_R;            // ink edge + one stroke of reveal = the rim

const mark = crown.children.find((c) => c.userData?.strokeWidth !== undefined);
if (!mark) throw new Error('make-favicon: no brand mark found on the built crown');

const { shapes, H, sw, r: fittedR } = brandMarkShapes({ r: MARK_R, tubeR: TUBE_R });
if (Math.abs(fittedR - mark.userData.r) > 1e-9 || Math.abs(sw - mark.userData.strokeWidth) > 1e-9)
  throw new Error(`make-favicon: sized ${fittedR}/${sw}, but the crown's mark is ` +
    `${mark.userData.r}/${mark.userData.strokeWidth} — the icon would not be the part's mark`);

// Shapes are in the mark's own frame: x about the centre, y from 0 (baseline)
// to H (cap line). Sample every outline, then fit the lot into a square.
const outlines = shapes.map((sh) => sh.getPoints(ARC_DIVISIONS));
let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
for (const pts of outlines) for (const p of pts) {
  if (p.x < minX) minX = p.x; if (p.x > maxX) maxX = p.x;
  if (p.y < minY) minY = p.y; if (p.y > maxY) maxY = p.y;
}
const inkW = maxX - minX, inkH = maxY - minY;

// A SQUARE canvas, because that is what every consumer of a favicon wants, with
// the mark centred in it. The quiet margin is ONE STROKE WIDTH — the same
// reveal makeCrown leaves between the mark's ink edge and the cap's face rim
// (markR + tubeR of ink, + tubeR of reveal, = the rim). The icon inherits the
// part's own spacing rule instead of inventing a padding number.
const side = Math.max(inkW, inkH) + 2 * sw;
const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2;
const x0 = cx - side / 2, y0 = cy - side / 2;

// SVG's y axis points down and the mark's points up, so every y is flipped
// about the canvas centre. Done here rather than with a transform so the path
// data reads as coordinates a human can check against the geometry.
const N = 4;                                  // decimals; ~1e-4 of a viewBox unit
const fx = (x) => Number((x - x0).toFixed(N));
const fy = (y) => Number((y0 + side - y).toFixed(N));
const path = outlines
  .map((pts) => `M${pts.map((p, i) => `${i ? 'L' : ''}${fx(p.x)},${fy(p.y)}`).join(' ')}Z`)
  .join('');

const GROUND = '#0b0d10';                     // index.html / manifest background_color
const INK = '#d6d9dd';                        // MATS.steel color, src/materials.js
// Corner radius: an eighth of the side. The only figure here with no source in
// the part — a crown face is round and an icon is not, so the rounding is a
// pure icon decision and is called one rather than dressed up as derived.
const R = Number((side / 8).toFixed(N));
const S = Number(side.toFixed(N));

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${S} ${S}" role="img" aria-label="WS monogram">
<title>Watch Sim</title>
<!-- GENERATED by tools/make-favicon.mjs from brandMarkShapes() in src/geometry.js
     (the §41 WS monogram on the winding crown). Do not hand-edit: re-run
     that tool (see its header for the exact invocation) to regenerate. -->
<rect width="${S}" height="${S}" rx="${R}" fill="${GROUND}"/>
<path fill="${INK}" fill-rule="nonzero" d="${path}"/>
</svg>
`;

// XML forbids "--" ANYWHERE inside a comment's content, not just at the
// close — Chromium's SVG parser rejects a comment that breaks this rule and
// renders its OWN parse-error page in place of the icon, silently: no
// exception here, no broken-image glyph in the browser, just the wrong
// picture. Caught only by actually looking at the rendered PNG. Checked
// here so a future edit to the header comment cannot reintroduce it unseen.
const commentBody = svg.match(/<!--([\s\S]*?)-->/)[1];
if (commentBody.includes('--'))
  throw new Error(`make-favicon: the header comment contains "--", which is illegal inside an XML comment and breaks the SVG parser: ${JSON.stringify(commentBody)}`);

writeFileSync(join(ROOT, 'favicon.svg'), svg);
console.log(`make-favicon: favicon.svg — ${shapes.length} outlines, ink ${inkW.toFixed(3)}x${inkH.toFixed(3)}, ` +
  `canvas ${S} (margin = one stroke ${sw.toFixed(3)}), ${svg.length} bytes`);

// RASTERIZE to PNG using Playwright. Two sizes: favicon.png (32×32, the standard
// size property for favicon.ico, used as fallback when SVG is not supported) and
// apple-touch-icon.png (180×180, iOS app icon). Both use the same SVG source, so
// hand-drawing a raster cannot happen — they stay a derived consequence of the
// monogram, which is the same discipline as the SVG.
const renderPNG = async (width, height, filename) => {
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({ deviceScaleFactor: 1 });
    const page = await context.newPage();
    const svgData = readFileSync(join(ROOT, 'favicon.svg'), 'utf8');
    const dataUrl = `data:image/svg+xml;base64,${Buffer.from(svgData).toString('base64')}`;
    await page.goto(dataUrl, { waitUntil: 'load' });
    await page.setViewportSize({ width, height });
    const png = await page.screenshot({ type: 'png' });
    writeFileSync(join(ROOT, filename), png);
    await context.close();
  } finally {
    await browser.close();
  }
};

await renderPNG(32, 32, 'favicon.png');
console.log(`make-favicon: favicon.png — 32×32, Safari fallback for SVG`);
await renderPNG(180, 180, 'apple-touch-icon.png');
console.log(`make-favicon: apple-touch-icon.png — 180×180, iOS home screen`);
