// TODO 158 — WRITE OR CHECK src/validated-configs.js, the set of configuration
// keys the battery has swept. ACCEPTANCE (--check exits non-zero on drift).
//
// The keys are never typed: this tool computes them by importing src/layout.js
// in Node (it has no imports and reads no page state), exactly the function
// the page calls, so the committed file cannot disagree with the build about
// what a key looks like. The explain-i18n --extract precedent.
//
//   node tools/validated-configs.mjs --write   regenerate the file
//   node tools/validated-configs.mjs --check   fail if the file is stale
//
// Tier A sweeps ONE configuration, the identity (default spec, no route, no
// geometry-bearing tuning). Tier B (TODO 186) would add the spec points a
// restricted sweep proves clean; each would then carry its own evidence row.
// The battery re-verifies every entry each run (tools/ci-battery.mjs's
// validated-configs gates), so an entry naming a key no run reproduces fails
// as stale — the closed-ratchet shape of UNDECLARED_CLEARANCE_DEBT.
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(ROOT, 'src/validated-configs.js');
const { configKey } = await import(join(ROOT, 'src/layout.js'));

export const EXPECTED = [{ point: 'identity', key: configKey(), evidence: 'battery: full sweep of the default build' }];

export function render(rows = EXPECTED) {
  return `// GENERATED by tools/validated-configs.mjs --write — never edit by hand.
//
// TODO 158 — the configuration keys (src/layout.js configKey) the inspector
// battery has swept. The page marks any build whose key is not listed as an
// UNVERIFIED configuration; the battery re-verifies every row each run and
// fails on a stale one. Adding a row is a claim that a sweep covered it.
export const VALIDATED_CONFIGS = Object.freeze([
${rows.map((r) => `  Object.freeze({ point: ${JSON.stringify(r.point)}, key: ${JSON.stringify(r.key)}, evidence: ${JSON.stringify(r.evidence)} }),`).join('\n')}
]);
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const want = render();
  if (process.argv.includes('--write')) {
    writeFileSync(FILE, want);
    console.log(`wrote src/validated-configs.js — ${EXPECTED.length} key(s): ${EXPECTED.map((r) => r.point).join(', ')}`);
  } else {
    let have = '';
    try { have = readFileSync(FILE, 'utf8'); } catch { /* missing reads as stale */ }
    if (have !== want) {
      console.error('src/validated-configs.js is STALE — the default configuration key moved. Run: node tools/validated-configs.mjs --write');
      process.exit(1);
    }
    console.log(`validated-configs OK — ${EXPECTED.length} key(s)`);
  }
}
