// §95 tier two — GERMAN. primer.html's prose, keyed by the English source
// (normalized innerHTML for rich blocks, text for plate labels); see
// src/page-i18n.js for the mechanism and src/primer-i18n.js for this page's
// number rule.
//
// Vocabulary is the Glashutte register, the SAME one tier one's chrome and
// the explainer use (src/i18n.js, src/explain-i18n.de.js): Unruh, Anker,
// Ankerrad, Spirale, Schnecke, Zeigerwerk. One movement cannot have two names
// for a part. The going train is named the way a German watchmaker names it --
// Grossbodenrad, Minutenrad, Kleinbodenrad, Sekundenrad, Ankerrad -- which is
// NOT a transliteration of "great / centre / third / fourth".
//
// NUMBERS ARE LOCALIZED HERE, and that is the deliberate inverse of
// explain-i18n.de.js. That page quotes identifiers, so 0.15 must stay 0.15;
// this page quotes nothing, so its numbers are quantities being read aloud and
// German gets them as German writes them: 4.800, 18.000, 0,024 mm. The checker
// compares VALUES, not glyphs, so the punctuation is free and the quantity is
// not -- write 0,25 for 0,024 and the build fails.
//
// EDITING THE ENGLISH INVALIDATES ITS TRANSLATION, ON PURPOSE: the key stops
// matching and that block renders English until someone re-translates it.
// Never retype a key -- `node tools/explain-i18n.mjs --extract --page primer`
// regenerates them from the DOM.
export default {

  // ---- page ----
  ['Watch Sim — A Primer']: 'Watch Sim — Eine Einführung',
  ['← the movement']: '← zum Werk',
  ['want the numbers? →']: 'Zahlen dazu? →',
  ['quantities rounded, with units · no source identifiers']: 'gerundete Größen mit Einheiten · keine Quelltext-Bezeichner',
  ['What you are looking at is a <b>fusee-and-chain watch movement</b>: a machine that stores a day\'s energy in a bent ribbon of steel and spends it five clicks at a time, on the say-so of a wheel that swings back and forth two and a half times a second. This page explains how, for a reader with a little physics and no horology. Every quantity here is rounded and carries its unit; none of it requires the source code. The companion page — <a href="./explain.html">Mechanisms</a> — is the opposite document: the same machine with every number quoted exactly from the source, for readers who want to check.']:
    'Sie sehen ein <b>Uhrwerk mit Schnecke und Kette</b>: eine Maschine, die die Energie eines Tages in einem gebogenen Stahlband speichert und sie fünf Klicks auf einmal ausgibt — auf Geheiß eines Rades, das zweieinhalb Mal pro Sekunde hin und her schwingt. Diese Seite erklärt, wie das geht, für Leser mit etwas Physik und ohne Uhrmacherei. Jede Größe hier ist gerundet und trägt ihre Einheit; nichts davon verlangt den Quelltext. Die Schwesterseite — <a href="./explain.html">Mechanismen</a> — ist das gegenteilige Dokument: dieselbe Maschine mit jeder Zahl exakt aus dem Quelltext zitiert, für Leser, die nachrechnen wollen.',
  ['<div class="sheet"> This page is maintained with the movement, in plain quantities — rounded, with units, and free of source identifiers by contract (a check enforces it). For the same mechanisms with every number quoted exactly from the source, see <a href="./explain.html">Mechanisms — how they work</a>. This project was made possible by <b>Claude</b>, Anthropic\'s AI model: the movement, its instruments and these pages were designed and built in collaboration with it. </div>']:
    '<div class="sheet"> Diese Seite wird mit dem Werk gepflegt, in schlichten Größen — gerundet, mit Einheiten und vertraglich frei von Quelltext-Bezeichnern (eine Prüfung hält das fest). Dieselben Mechanismen mit jeder Zahl exakt aus dem Quelltext zitiert finden Sie unter <a href="./explain.html">Mechanismen — so funktionieren sie</a>. Dieses Projekt wurde durch <b>Claude</b> möglich, das KI-Modell von Anthropic: das Uhrwerk, seine Prüfinstrumente und diese Seiten wurden in Zusammenarbeit mit ihm entworfen und gebaut. </div>',

  // ---- energy ----
  ['Wind a watch and you are bending steel. The mainspring is a long, thin ribbon coiled inside a drum: its outer end is riveted to the drum wall, its inner end is hooked to a shaft that stands still. Winding does not <em>rotate</em> the spring so much as change its <em>shape</em> — the same length of ribbon crowds into tight turns near the centre, and the energy of a wind is stored the way a drawn bow stores it, in elastic bending all along the ribbon\'s length.']:
    'Eine Uhr aufziehen heißt Stahl biegen. Die Zugfeder ist ein langes, dünnes Band, aufgerollt im Federhaus: ihr äußeres Ende ist an der Federhauswand vernietet, ihr inneres Ende an einem Federkern eingehängt, der stillsteht. Aufziehen <em>dreht</em> die Feder also weniger, als dass es ihre <em>Form</em> ändert — dieselbe Bandlänge drängt sich in enge Windungen nahe der Mitte, und die Energie eines Aufzugs steckt wie in einem gespannten Bogen in der elastischen Biegung über die ganze Bandlänge.',
  ['As the watch runs, the ribbon relaxes turn by turn and its stored energy flows out through the drum. One full wind here holds about <b>30 hours</b> of running, and the machinery spends it very slowly: the first wheel of the gear train makes one revolution every 17 1/7 hours — one and three-quarter turns over the whole reserve. Everything faster than that is gearing, which has its own entry below.']: 'Während die Uhr läuft, entspannt sich das Band Windung um Windung, und seine gespeicherte Energie fließt durch das Federhaus ab. Ein voller Aufzug trägt hier rund <b>30 Stunden</b> Gang, und das Werk gibt sie sehr langsam aus: das erste Rad des Räderwerks macht eine Umdrehung alle 17 1/7 Stunden — eindreiviertel Umdrehungen über die ganze Gangreserve. Alles Schnellere ist Übersetzung, die ihren eigenen Eintrag weiter unten hat.',
  ['Honesty note: the ribbon in the simulation is not a decoration. Its shape is recomputed as the wind changes, under two constraints a real spring obeys — neighbouring turns may touch but never merge, and every shape must be the same length of steel, because steel does not stretch. The picture of a wound spring bunched at the centre and a spent one spread against the wall is the geometry those two rules force.']:
    'Ehrlichkeitsnotiz: das Band in der Simulation ist keine Verzierung. Seine Form wird mit jedem Wickelzustand neu gerechnet, unter zwei Bedingungen, denen eine echte Feder gehorcht — benachbarte Windungen dürfen sich berühren, aber nie verschmelzen, und jede Form muss dieselbe Länge Stahl sein, denn Stahl dehnt sich nicht. Das Bild einer aufgezogenen Feder, die sich in der Mitte drängt, und einer abgelaufenen, die sich an der Wand ausbreitet, ist die Geometrie, die diese beiden Regeln erzwingen.',
  ['Where the energy comes from<span class="where">power</span>']: 'Woher die Energie kommt<span class="where">Kraft</span>',

  // ---- fusee ----
  ['A spring\'s pull is not constant: freshly wound it is strong, nearly spent it is weak. A timekeeper hates that, because the size of the push reaching the balance changes how it swings. The classical fix — this movement\'s namesake — is the <b>fusee</b>: a cone-shaped pulley connected to the spring\'s drum by a miniature chain — built like a bicycle chain, with links well under a millimetre long.']:
    'Der Zug einer Feder ist nicht konstant: frisch aufgezogen ist er stark, fast abgelaufen schwach. Einer Uhr behagt das nicht, denn die Größe des Antriebs, der die Unruh erreicht, ändert damit ihren Schwung. Die klassische Abhilfe — der Namensgeber dieses Werks — ist die <b>Schnecke</b>: eine kegelförmige Seilrolle, mit dem Federhaus durch eine winzige Kette verbunden — gebaut wie eine Fahrradkette, mit Gliedern deutlich unter einem Millimeter Länge.',
  ['The trick is leverage. Torque — turning force — is pull times lever arm. When the spring is strong, the chain pulls on the cone\'s <em>narrow</em> end: big pull, short lever. As the spring runs down, the chain walks along the cone\'s spiral groove toward the <em>wide</em> end: smaller pull, longer lever. The product, the torque handed to the gears, stays nearly level from full wind to empty.']:
    'Der Kniff ist die Hebelwirkung. Drehmoment — Drehkraft — ist Zug mal Hebelarm. Ist die Feder stark, zieht die Kette am <em>schmalen</em> Ende des Kegels: großer Zug, kurzer Hebel. Läuft die Feder ab, wandert die Kette in der spiraligen Rille zum <em>weiten</em> Ende: kleinerer Zug, längerer Hebel. Das Produkt, das an das Räderwerk abgegebene Drehmoment, bleibt nahezu gleich von vollem Aufzug bis leer.',
  ['The cone is cut against the spring\'s own measured decline, so the two curves cancel. The chain also explains the winding feel of such watches: winding spools the chain back from drum to cone, and a small detent keeps the gears driven during the seconds the wind would otherwise unload them.']:
    'Der Kegel ist gegen den gemessenen eigenen Abfall der Feder geschnitten, sodass sich die beiden Kurven aufheben. Die Kette erklärt auch das Aufzugsgefühl solcher Uhren: Aufziehen spult die Kette vom Federhaus zurück auf den Kegel, und eine kleine Sperrung hält das Räderwerk angetrieben, während der Aufzug es sonst kurz entlasten würde.',
  ['The fusee — evening out a dying spring<span class="where">power</span>']:
    'Die Schnecke — den Abfall einer sterbenden Feder ausgleichen<span class="where">Kraft</span>',
  ['Pull × lever arm ≈ constant']: 'Zug × Hebelarm ≈ konstant',
  ['PLATE 1']: 'TAFEL 1',
  ['freshly wound']: 'frisch aufgezogen',
  ['short lever']: 'kurzer Hebel',
  ['strong pull']: 'starker Zug',
  ['big pull × small radius']: 'großer Zug × kleiner Radius',
  ['nearly run down']: 'fast abgelaufen',
  ['long lever']: 'langer Hebel',
  ['weak pull']: 'schwacher Zug',
  ['small pull × big radius']: 'kleiner Zug × großer Radius',
  ['≈ the same torque']: '≈ dasselbe Drehmoment',

  // ---- gears ----
  ['Everything between the drum and the ticking is multiplication. When a wheel with many teeth drives a small pinion, the pinion turns faster in exact proportion to the tooth counts — a wheel of 120 teeth driving a pinion of 7 turns it exactly 17 1/7 times per revolution, and there is nothing more to know. Speed is bought at the price of force, the same trade as a bicycle\'s gears.']: 'Alles zwischen dem Federhaus und dem Ticken ist Multiplikation. Treibt ein Rad mit vielen Zähnen ein kleines Trieb, dreht sich das Trieb genau im Verhältnis der Zähnezahlen schneller — ein Rad mit 120 Zähnen an einem Trieb mit 7 dreht dieses genau 17 1/7 Mal je Umdrehung, und mehr gibt es dazu nicht zu wissen. Geschwindigkeit wird mit Kraft bezahlt, derselbe Handel wie bei den Gängen eines Fahrrads.',
  ['Four such steps stand between the power and the escapement. The last three you can check on your fingers: 7½ × 8 × 10 = 600, which is exactly one turn per hour becoming one turn every 6 seconds. The first step is the odd fraction, × 17 1/7: the "great wheel", riding on the fusee cone itself, turns once in 17 1/7 hours, and its 120 teeth driving a 7-leaf pinion hand the centre wheel its once-per-hour turn. That gearing was chosen for the chain\'s sake — spreading the 30-hour reserve over fewer, wider-spaced turns of groove is what gives every link room to sit flat against the cone instead of perching on a corner.']: 'Vier solcher Stufen stehen zwischen der Kraft und der Hemmung. Die letzten drei können Sie an den Fingern nachrechnen: 7½ × 8 × 10 = 600, genau der Schritt von einer Umdrehung je Stunde zu einer Umdrehung alle 6 Sekunden. Die erste Stufe ist der krumme Bruch, × 17 1/7: das „Großbodenrad“, das auf dem Schneckenkegel selbst sitzt, dreht sich einmal in 17 1/7 Stunden, und seine 120 Zähne an einem 7-flügeligen Trieb geben dem Zentrumsrad seine Umdrehung je Stunde. Diese Übersetzung wurde der Kette zuliebe gewählt — die 30-Stunden-Reserve auf weniger, weiter auseinanderliegende Rillenwindungen zu verteilen ist es, was jedem Glied den Platz gibt, flach am Kegel anzuliegen, statt auf einer Ecke zu balancieren.',
  ['The hour hand is one more piece of the same arithmetic. A small gear turning with the minute hand drives a wheel three times its size, and a pinion on that wheel drives the hour wheel at 4:1 more — 3 × 4 = <b>12:1</b>, which is why the hour hand makes one circuit while the minute hand makes twelve. In this simulation that ratio is never written down anywhere: it emerges because those four tooth counts multiply to it, exactly as in the metal.']:
    'Der Stundenzeiger ist ein weiteres Stück derselben Rechnung. Ein kleines Rad, das mit dem Minutenzeiger läuft, treibt ein Rad von dreifacher Größe, und ein Trieb auf diesem Rad treibt das Stundenrad noch einmal mit 4:1 — 3 × 4 = <b>12:1</b>, weshalb der Stundenzeiger einen Umlauf macht, während der Minutenzeiger zwölf macht. In dieser Simulation steht dieses Verhältnis nirgends geschrieben: es entsteht, weil jene vier Zähnezahlen sich dazu multiplizieren, genau wie im Metall.',
  ['Two of the train\'s wheels double as the display: the centre wheel turns once an hour and carries the minute hand; the fourth wheel turns once a minute and carries the seconds hand. No hand is ever <em>told</em> where to point — its angle arrives through the teeth.']:
    'Zwei Räder des Räderwerks sind zugleich die Anzeige: das Minutenrad dreht sich einmal je Stunde und trägt den Minutenzeiger; das Sekundenrad dreht sich einmal je Minute und trägt den Sekundenzeiger. Keinem Zeiger wird je <em>gesagt</em>, wohin er zeigen soll — sein Winkel kommt durch die Zähne.',
  ['Gears are arithmetic<span class="where">power → display</span>']: 'Räderwerk ist Rechnen<span class="where">Kraft → Anzeige</span>',
  ['One turn in 17 1/7 hours becomes one turn in 6 seconds']: 'Eine Umdrehung in 17 1/7 Stunden wird zu einer in 6 Sekunden',
  ['great wheel · 120 teeth']: 'Großbodenrad · 120 Zähne',
  ['1 turn / 17 1/7 h']: '1 Umdr. / 17 1/7 h',
  ['× 17 1/7']: '× 17 1/7',
  ['× 8']: '× 8',
  ['centre wheel']: 'Minutenrad',
  ['1 turn / hour']: '1 Umdr. / Stunde',
  ['carries the minute hand']: 'trägt den Minutenzeiger',
  ['× 7½']: '× 7½',
  ['third wheel']: 'Kleinbodenrad',
  ['fourth wheel']: 'Sekundenrad',
  ['1 turn / minute']: '1 Umdr. / Minute',
  ['carries the seconds hand']: 'trägt den Sekundenzeiger',
  ['× 10']: '× 10',
  ['escape wheel']: 'Ankerrad',
  ['1 turn / 6 s']: '1 Umdr. / 6 s',

  // ---- escapement ----
  ['Left alone, the gear train would spin the whole reserve away in moments. The <b>escapement</b> is the checkout counter: it lets the train advance one fixed step at a time, and only when the timekeeper says so. Its three players are the escape wheel (the train\'s last, fastest wheel), a see-sawing lever with two jewelled pallet stones, and the balance — the swinging wheel of the next entry.']:
    'Sich selbst überlassen würde das Räderwerk die ganze Gangreserve in Augenblicken verdrehen. Die <b>Hemmung</b> ist die Kasse: sie lässt das Räderwerk um jeweils einen festen Schritt vorrücken, und nur dann, wenn der Zeitmesser es sagt. Ihre drei Mitspieler sind das Ankerrad (das letzte, schnellste Rad des Werks), ein wippender Anker mit zwei Rubinpaletten und die Unruh — das schwingende Rad des nächsten Eintrags.',
  ['Most of the time the escape wheel is simply <em>held</em>: a tooth presses on a stone, and the geometry of the stone\'s face is angled so that the pressure locks it tighter rather than slipping — like a door wedge that a push only seats deeper. When the swinging balance flicks the lever, the stone lifts, the wheel escapes forward by <b>12°</b> — half a tooth spacing, no more, because the lever\'s other stone is already in the way — and in that brief slide the tooth\'s face pushes on the stone, handing the balance a small shove that pays back what friction and air took from its swing. Then the wheel is caught again, and waits.']:
    'Meist wird das Ankerrad schlicht <em>gehalten</em>: ein Zahn drückt auf eine Palette, und die Fläche der Palette ist so geneigt, dass der Druck sie fester sperrt statt sie rutschen zu lassen — wie ein Türkeil, den ein Stoß nur tiefer setzt. Wenn die schwingende Unruh den Anker anstößt, hebt die Palette ab, das Rad entkommt um <b>12°</b> nach vorn — eine halbe Zahnteilung, nicht mehr, weil die andere Palette schon wartet — und in diesem kurzen Gleiten drückt die Zahnfläche auf die Palette und gibt der Unruh einen kleinen Stoß, der ihr zurückzahlt, was Reibung und Luft ihrem Schwung genommen haben. Dann wird das Rad wieder gefangen und wartet.',
  ['That cycle is the tick: <b>5 per second</b> here, 18,000 per hour, each one an unlock–slide–catch. The wheel is in motion for only about a sixth of each beat — a watch is a machine that is almost always standing still.']:
    'Dieser Ablauf ist das Ticken: hier <b>5 je Sekunde</b>, 18.000 je Stunde, jedes ein Entsperren–Gleiten–Fangen. Das Rad ist nur etwa ein Sechstel jedes Schlages in Bewegung — eine Uhr ist eine Maschine, die fast immer stillsteht.',
  ['Two ideas travel through one contact, in opposite directions. Energy flows outward: train → wheel → stone → lever → balance, a shove per beat. Position flows inward: the wheel stands where the stones allow, so the balance — not the spring in the drum — decides what time it is.']:
    'Zwei Gedanken laufen durch denselben Kontakt, in entgegengesetzte Richtungen. Energie fließt nach außen: Räderwerk → Rad → Palette → Anker → Unruh, ein Stoß je Schlag. Die Stellung läuft nach innen: das Rad steht dort, wo die Paletten es zulassen, also entscheidet die Unruh — nicht die Feder im Federhaus —, wie spät es ist.',
  ['The escapement — spending energy five clicks a second<span class="where">timekeeping</span>']:
    'Die Hemmung — Energie ausgeben, fünf Klicks je Sekunde<span class="where">Zeitmessung</span>',
  ['Held, then let go — one step at a time']: 'Gehalten, dann losgelassen — Schritt für Schritt',
  ['locked — most of the beat']: 'gesperrt — der größte Teil des Schlags',
  ['stone holds the tooth']: 'Palette hält den Zahn',
  ['pressure seats it deeper']: 'Druck setzt sie tiefer',
  ['the train pushes; nothing moves']: 'das Werk drückt; nichts bewegt sich',
  ['impulse — a sixth of the beat']: 'Antrieb — ein Sechstel des Schlags',
  ['tooth shoves the stone,']: 'Zahn stößt die Palette,',
  ['flicking lever + balance']: 'Anker + Unruh folgen',
  ['the wheel advances 12° and is caught']: 'das Rad rückt 12° vor und wird gefangen',

  // ---- balance ----
  ['The timekeeper itself is the <b>balance</b>: a weighted rim on pivots, with a spiralled hairspring that twists as the rim turns and pushes it back toward centre. Twist it further, and the spring pushes back harder — restoring torque proportional to angle. Newton\'s law for rotation then gives the balance\'s angular acceleration as spring stiffness over rotational inertia, times the angle — and that equation is the same one a mass on a spring obeys. Its solution is a steady oscillation whose frequency depends on exactly two things: the <em>stiffness</em> of the spring and the <em>inertia</em> of the wheel. Frequency is the square root of stiffness over inertia — and nothing else.']:
    'Der Zeitmesser selbst ist die <b>Unruh</b>: ein beschwerter Reif auf Zapfen, mit einer spiralig gewundenen Spirale, die sich mit dem Reif verdreht und ihn zur Mitte zurückdrückt. Verdreht man weiter, drückt die Spirale stärker zurück — Rückstellmoment proportional zum Winkel. Newtons Gesetz für die Drehung gibt dann die Winkelbeschleunigung der Unruh als Federsteifigkeit geteilt durch Trägheitsmoment, mal dem Winkel — und das ist dieselbe Gleichung, der eine Masse an einer Feder gehorcht. Ihre Lösung ist eine gleichmäßige Schwingung, deren Frequenz von genau zwei Dingen abhängt: der <em>Steifigkeit</em> der Spirale und der <em>Trägheit</em> des Rades. Die Frequenz ist die Wurzel aus Steifigkeit durch Trägheit — und aus sonst nichts.',
  ['The remarkable consequence: the <em>amplitude is not in the formula</em>. Swing the balance wide or barely at all and each swing takes the same time — a big swing moves faster through a longer arc, and the two effects cancel. That property, called <b>isochronism</b>, is why a watch can keep time while its mainspring\'s push (and so its balance\'s swing) sags across 30 hours. Galileo noticed it in a swinging lamp; every mechanical watch since is a bet placed on it.']:
    'Die bemerkenswerte Folge: die <em>Amplitude steht nicht in der Formel</em>. Lassen Sie die Unruh weit oder kaum schwingen — jede Schwingung dauert gleich lang, denn ein weiter Ausschlag läuft schneller durch einen längeren Bogen, und beides hebt sich auf. Diese Eigenschaft, <b>Isochronismus</b> genannt, ist der Grund, weshalb eine Uhr Zeit halten kann, während der Antrieb ihrer Zugfeder (und damit der Ausschlag ihrer Unruh) über 30 Stunden nachlässt. Galilei bemerkte sie an einer schwingenden Lampe; jede mechanische Uhr seither ist eine Wette darauf.',
  ['The physics also says how to <em>adjust</em> such a watch. This balance is "free-sprung": nothing ever pinches or shortens the hairspring. Instead the rim carries threaded timing screws — screw a pair inward and the rim\'s mass moves toward the axis, the inertia drops, and the watch runs faster; outward, slower. Rate lives in the denominator of that square root.']:
    'Die Physik sagt auch, wie man eine solche Uhr <em>reguliert</em>. Diese Unruh ist „frei schwingend“: nichts klemmt oder verkürzt je die Spirale. Stattdessen trägt der Reif eingeschraubte Regulierschrauben — dreht man ein Paar hinein, wandert Masse des Reifs zur Achse, die Trägheit sinkt und die Uhr geht vor; heraus, nach. Der Gang sitzt im Nenner jener Wurzel.',
  ['Honesty note: in this simulation the spring is real arithmetic, not a prop. The wheel\'s inertia is computed from its drawn dimensions — about 85% of it in the rim, a tenth in the screws, the rest in the arms — and the hairspring\'s cross-section is then <em>solved</em> so that the square root lands exactly on the advertised rate. The ribbon that comes out of the solve is about 0.024 mm thick, inside the 0.02–0.04 mm range real hairspring stock is drawn in. The one liberty is the drawn amplitude, above.']:
    'Ehrlichkeitsnotiz: in dieser Simulation ist die Spirale echte Rechnung, keine Attrappe. Die Trägheit des Rades wird aus seinen gezeichneten Abmessungen gewogen — etwa 85 % davon im Reif, ein Zehntel in den Schrauben, der Rest in den Armen — und der <em>Querschnitt</em> der Spirale wird dann so gelöst, dass die Wurzel genau auf der angegebenen Frequenz landet. Das Band, das aus dieser Lösung kommt, ist rund 0,024 mm dick und liegt damit im Bereich 0,02–0,04 mm, in dem echtes Spiralfederband gezogen wird. Die eine Freiheit ist die gezeichnete Amplitude, siehe oben.',
  ['Here the balance completes 2½ full oscillations per second, and each oscillation crosses the escapement twice — once each way — giving the 5 ticks per second of the previous entry. A healthy real balance swings roughly three-quarters of a turn each way; on screen the swing is drawn smaller than life so the beat stays readable at a glance.']:
    'Hier vollführt die Unruh 2½ volle Schwingungen je Sekunde, und jede Schwingung quert die Hemmung zweimal — je Richtung einmal —, was die 5 Ticks je Sekunde des vorigen Eintrags ergibt. Eine gesunde echte Unruh schwingt etwa drei Viertel einer Umdrehung je Seite; auf dem Schirm ist der Ausschlag kleiner gezeichnet als in Wirklichkeit, damit der Schlag auf einen Blick lesbar bleibt.',
  ['Why the balance keeps time<span class="where">timekeeping</span>']: 'Warum die Unruh die Zeit hält<span class="where">Zeitmessung</span>',
  ['Big swing or small — the same time per swing']: 'Weit oder eng — dieselbe Zeit je Schwingung',
  ['wide swing']: 'weiter Ausschlag',
  ['long arc, high speed']: 'langer Bogen, hohe Geschwindigkeit',
  ['narrow swing']: 'enger Ausschlag',
  ['short arc, low speed']: 'kurzer Bogen, geringe Geschwindigkeit',
  ['same period —']: 'gleiche Dauer —',
  ['2½ swings per second']: '2½ Schwingungen je Sekunde',

  // ---- keyless ----
  ['The crown at the movement\'s edge does two unrelated things — winds the spring, sets the hands — and the mechanism that decides which is a small axial clutch on the crown\'s stem. Pushed home, the stem\'s gear engages the winding path: each turn of the crown spools chain back onto the fusee cone, storing energy. Pulled out one stop, a pivoting lever slides that gear a couple of millimetres along the stem into the setting path, where it reaches the hand wheels instead.']:
    'Die Krone am Rand des Werks tut zwei ganz verschiedene Dinge — die Feder aufziehen, die Zeiger stellen — und was gerade gilt, entscheidet eine kleine axiale Kupplung auf der Aufzugswelle. Eingedrückt greift das Trieb der Welle in den Aufzugsweg: jede Drehung der Krone spult Kette zurück auf den Schneckenkegel und speichert Energie. Eine Raste herausgezogen, schiebt ein schwenkender Hebel dasselbe Trieb ein paar Millimeter längs der Welle in den Stellweg, wo es stattdessen das Zeigerwerk erreicht.',
  ['One crown, two jobs<span class="where">interface</span>']: 'Eine Krone, zwei Aufgaben<span class="where">Bedienung</span>',

  // ---- alarm ----
  ['This movement carries a complete second power system for its alarm, with its own crown, its own barrel-spring, and its own release. The alarm crown does for the alarm what the main crown does for the time: turned one way it sets a disc under the dial to the chosen alarm time (a central alarm hand shows it, riding beneath the hour hand); pushed home it winds the alarm\'s own spring.']:
    'Dieses Werk trägt ein vollständiges zweites Kraftsystem für seinen Wecker, mit eigener Krone, eigener Weckerfeder und eigener Auslösung. Die Weckerkrone tut für den Wecker, was die Hauptkrone für die Zeit tut: in die eine Richtung gedreht stellt sie eine Scheibe unter dem Zifferblatt auf die gewählte Weckzeit (ein zentraler Weckzeiger zeigt sie an und läuft unter dem Stundenzeiger); eingedrückt zieht sie die eigene Feder des Weckers auf.',
  ['The release is a mechanical comparison, made by touch. A spring-loaded finger — the <b>feeler</b> — rests against the edge of the rotating alarm disc, which turns with the hours. The disc\'s edge carries a notch at the set time; everywhere else the feeler rides the high rim and the alarm stays blocked. When the dial\'s time reaches the set time, the notch arrives under the feeler, the feeler drops in, and the block is withdrawn: the alarm spring is free to run. It spins a small train that swings a hammer against a gong, and rings until the spring is spent — or until a pull of the alarm crown lifts the feeler out and parks it.']:
    'Die Auslösung ist ein mechanischer Vergleich, ertastet. Ein gefederter Finger — der <b>Fühlhebel</b> — liegt am Rand der umlaufenden Weckerscheibe an, die mit den Stunden dreht. Der Rand der Scheibe trägt an der eingestellten Zeit eine Kerbe; überall sonst läuft der Fühlhebel auf dem hohen Rand und der Wecker bleibt gesperrt. Erreicht die Zeit des Zifferblatts die eingestellte Zeit, kommt die Kerbe unter den Fühlhebel, er fällt ein, und die Sperre ist weg: die Weckerfeder darf laufen. Sie treibt ein kleines Räderwerk, das einen Hammer gegen die Gongfeder schwingt, und schlägt, bis die Feder erschöpft ist — oder bis ein Zug an der Weckerkrone den Fühlhebel aushebt und parkt.',
  ['Arming is its own little machine: pressing the pusher ratchets a star-shaped column wheel round one tooth per press, alternately enabling and disabling the release — the same switch-by-column that chronograph buttons use.']:
    'Das Scharfstellen ist eine eigene kleine Maschine: ein Druck auf den Drücker schaltet ein sternförmiges Schaltrad um je einen Zahn weiter und gibt die Auslösung abwechselnd frei und sperrt sie — dieselbe Umschaltung über ein Schaltrad, die auch Chronographendrücker verwenden.',
  // ---- §104: the ringing is driven now ----
  ['Honesty note, both directions. The arming chain is genuinely <em>driven</em>: the press moves the pawl, the pawl indexes the column, and every part downstream stands where the surface pushing it puts it — the simulation measures every one of those contacts closed on every test run. The ringing now is too: the hammer\'s <em>tempo</em> is derived from the spring\'s torque through the speed limiter real alarms use — a small anchor fluttering on a toothed wheel, its balancing ring sized by arithmetic — so the bell starts brisk on a full spring and audibly slows as it spends, stopping at a floor the spring\'s pre-tension sets instead of trailing off. What the debt list still records here: the hammer\'s own fall is timed from the strike schedule, not yet from its blade\'s stiffness.']: 'Ehrlichkeitsnotiz, in beide Richtungen. Die Kette des Scharfstellens ist tatsächlich <em>getrieben</em>: der Druck bewegt die Klinke, die Klinke schaltet das Schaltrad weiter, und jedes Teil stromabwärts steht dort, wohin die Fläche es setzt, die es schiebt — die Simulation misst jeden dieser Kontakte bei jedem Prüflauf als geschlossen. Das Läuten ist es jetzt auch: das <em>Tempo</em> des Hammers wird aus dem Drehmoment der Feder abgeleitet, durch die Drehzahlbremse, die echte Wecker verwenden — einen kleinen Anker, der auf einem Zahnrad flattert, mit einem nach Arithmetik bemessenen Schwungring —, sodass die Glocke bei voller Feder zügig beginnt, hörbar langsamer wird, während sie sich verausgabt, und an einem Boden stehen bleibt, den die Vorspannung der Feder setzt, statt einfach zu verhallen. Was die Schuldenliste hier noch verzeichnet: der Fall des Hammers selbst ist nach dem Schlagplan getaktet, noch nicht nach der Steifigkeit seiner Klinge.',
  ['The gap between those words is where simulations usually lie, and this one keeps a public ledger of exactly that gap. The hands are simulated — their angles arrive through tooth counts, never assigned. The arming run is simulated — measured contact by contact. The hairspring\'s stiffness is modelled honestly enough that the beat follows from it as arithmetic, and the alarm\'s ringing tempo — for a long time the ledger\'s standing example of a merely authored number — is now derived the same way, from its own spring through a governor. The ledger did not empty, it moved: the hammer\'s fall is still timed rather than sprung, and the debt list says so in writing rather than letting the animation imply otherwise.']: 'In der Lücke zwischen diesen Wörtern lügen Simulationen für gewöhnlich, und dieses Projekt führt über genau diese Lücke ein öffentliches Register. Die Zeiger sind simuliert — ihre Winkel kommen durch Zähnezahlen an, nie zugewiesen. Der Schärf-Lauf ist simuliert — Kontakt für Kontakt gemessen. Die Steifigkeit der Spirale ist ehrlich genug modelliert, dass der Takt als Arithmetik aus ihr folgt, und das Schlagtempo des Weckers — lange das stehende Beispiel des Registers für eine bloß gesetzte Zahl — ist jetzt auf dieselbe Weise abgeleitet, aus seiner eigenen Feder durch einen Regler. Das Register wurde nicht leer, es ist umgezogen: der Fall des Hammers ist noch getaktet statt gefedert, und die Schuldenliste sagt das schriftlich, statt die Animation etwas anderes andeuten zu lassen.',
  ['The alarm — a second spring with a voice<span class="where">alarm</span>']: 'Der Wecker — eine zweite Feder mit Stimme<span class="where">Wecker</span>',

  // ---- gong ----
  ['The alarm\'s voice is a steel bar clamped at one end — a stiff one-sided beam the hammer strikes near its foot. Strike any such bar and it rings at several frequencies at once: the fundamental, plus overtones whose positions are fixed by the physics of a bending beam, not by any tuner. For a clamped-free bar the second mode lands at about <b>6.3×</b> the fundamental — not 2×, not 3×, nothing on the musical ladder. Overtones that miss the whole-number rungs are what your ear calls "metallic"; a guitar string\'s overtones land exactly on them, which is why a string is a note and a struck bar is a <em>clang</em>.']:
    'Die Stimme des Weckers ist ein an einem Ende eingespannter Stahlstab — ein steifer einseitiger Balken, den der Hammer nahe seinem Fuß trifft. Schlägt man einen solchen Stab an, klingt er in mehreren Frequenzen zugleich: dem Grundton, dazu Obertöne, deren Lage die Physik eines biegenden Balkens festlegt, kein Stimmer. Bei einem einseitig eingespannten Stab liegt die zweite Eigenform bei etwa dem <b>6,3fachen</b> des Grundtons — nicht 2×, nicht 3×, auf keiner Sprosse der musikalischen Leiter. Obertöne, die die ganzzahligen Sprossen verfehlen, sind das, was Ihr Ohr „metallisch“ nennt; die Obertöne einer Gitarrensaite treffen sie genau, weshalb eine Saite ein Ton ist und ein angeschlagener Stab ein <em>Scheppern</em>.',
  ['In the simulation the sound is synthesised from the drawn bar itself: its length and thickness set the fundamental, the beam equation sets the overtone ratios, and shortening the bar raises every partial together — exactly as filing a real gong would. Nothing about the sound is a recording, and no frequency is picked by hand.']:
    'In der Simulation wird der Klang aus dem gezeichneten Stab selbst erzeugt: seine Länge und Dicke setzen den Grundton, die Balkengleichung setzt die Obertonverhältnisse, und ein Kürzen des Stabs hebt alle Teiltöne gemeinsam an — genau wie das Feilen einer echten Gongfeder. Nichts am Klang ist eine Aufnahme, und keine Frequenz ist von Hand gewählt.',
  ['Why the gong sounds like metal, not music<span class="where">alarm</span>']:
    'Warum der Gong nach Metall klingt und nicht nach Musik<span class="where">Wecker</span>',

  // ---- honesty ----
  ['This project polices its own language, and the primer is bound by the same rule as everything else. Two words are used precisely. <b>Modelled</b> means <em>described</em>: the geometry exists, its dimensions are derived from stated constraints, and instruments check the description for contradictions. <b>Simulated</b> means <em>driven</em>: the part moves because another part pushes it, cause to effect through real contacts — not because an animation poses it where the answer should be.']:
    'Dieses Projekt achtet auf seine eigene Sprache, und die Einführung ist an dieselbe Regel gebunden wie alles andere. Zwei Wörter werden genau verwendet. <b>Modelliert</b> heißt <em>beschrieben</em>: die Geometrie existiert, ihre Maße sind aus genannten Randbedingungen abgeleitet, und Instrumente prüfen die Beschreibung auf Widersprüche. <b>Simuliert</b> heißt <em>getrieben</em>: das Teil bewegt sich, weil ein anderes Teil es schiebt, Ursache zu Wirkung über echte Kontakte — nicht weil eine Animation es dorthin setzt, wo die Antwort sein sollte.',
  ['If a claim on this page overstates what the machine underneath actually does, that is a bug in this page — the ledger, not the prose, is the record.']:
    'Behauptet diese Seite mehr, als die Maschine darunter wirklich tut, dann ist das ein Fehler dieser Seite — das Verzeichnis ist die Aufzeichnung, nicht der Text.',
  ['What this simulation claims — and what it doesn\'t<span class="where">the rules</span>']:
    'Was diese Simulation behauptet — und was nicht<span class="where">die Regeln</span>',
};
