// §95 tier two — GERMAN. primer.html's prose, keyed by the English source
// (normalized innerHTML for rich blocks, text for plate labels); see
// src/page-i18n.js for the mechanism and src/primer-i18n.js for this page's
// number rule.
//
// Vocabulary is the Glashutte register, the SAME one tier one's chrome and
// the explainer use (src/i18n.js, src/explain-i18n.de.js): Unruh, Anker,
// Ankerrad, Spirale, Schnecke, Zeigerwerk. One movement cannot have two names
// for a part. The going train is named the way a German watchmaker names it --
// Grossbodenrad, Minutenrad, Kleinbodenrad, Sekundenrad, Ankerrad -- which is
// NOT a transliteration of "great / centre / third / fourth".
//
// NUMBERS ARE LOCALIZED HERE, and that is the deliberate inverse of
// explain-i18n.de.js. That page quotes identifiers, so 0.15 must stay 0.15;
// this page quotes nothing, so its numbers are quantities being read aloud and
// German gets them as German writes them: 4.800, 18.000, 0,024 mm. The checker
// compares VALUES, not glyphs, so the punctuation is free and the quantity is
// not -- write 0,25 for 0,024 and the build fails.
//
// EDITING THE ENGLISH INVALIDATES ITS TRANSLATION, ON PURPOSE: the key stops
// matching and that block renders English until someone re-translates it.
// Never retype a key -- `node tools/explain-i18n.mjs --extract --page primer`
// regenerates them from the DOM.
export default {

  // ---- page ----
  ['Watch Sim — A Primer']: 'Watch Sim — Eine Einführung',
  ['← the movement']: '← zum Werk',
  ['want the numbers? →']: 'Zahlen dazu? →',
  ['quantities rounded, with units · no source identifiers']: 'gerundete Größen mit Einheiten · keine Quelltext-Bezeichner',
  ['What you are looking at is a <b>fusee-and-chain watch movement</b>: a machine that stores a day\'s energy in a bent ribbon of steel and spends it five clicks at a time, on the say-so of a wheel that swings back and forth two and a half times a second. This page explains how, for a reader with a little physics and no horology. Every quantity here is rounded and carries its unit; none of it requires the source code. The companion page — <a href="./explain.html">Mechanisms</a> — is the opposite document: the same machine with every number quoted exactly from the source, for readers who want to check.']:
    'Sie sehen ein <b>Uhrwerk mit Schnecke und Kette</b>: eine Maschine, die die Energie eines Tages in einem gebogenen Stahlband speichert und sie fünf Klicks auf einmal ausgibt — auf Geheiß eines Rades, das zweieinhalb Mal pro Sekunde hin und her schwingt. Diese Seite erklärt, wie das geht, für Leser mit etwas Physik und ohne Uhrmacherei. Jede Größe hier ist gerundet und trägt ihre Einheit; nichts davon verlangt den Quelltext. Die Schwesterseite — <a href="./explain.html">Mechanismen</a> — ist das gegenteilige Dokument: dieselbe Maschine mit jeder Zahl exakt aus dem Quelltext zitiert, für Leser, die nachrechnen wollen.',
  ['<div class="sheet"> This page is maintained with the movement, in plain quantities — rounded, with units, and free of source identifiers by contract (a check enforces it). For the same mechanisms with every number quoted exactly from the source, see <a href="./explain.html">Mechanisms — how they work</a>. This project was made possible by <b>Claude</b>, Anthropic\'s AI model: the movement, its instruments and these pages were designed and built in collaboration with it. </div>']:
    '<div class="sheet"> Diese Seite wird mit dem Werk gepflegt, in schlichten Größen — gerundet, mit Einheiten und vertraglich frei von Quelltext-Bezeichnern (eine Prüfung hält das fest). Dieselben Mechanismen mit jeder Zahl exakt aus dem Quelltext zitiert finden Sie unter <a href="./explain.html">Mechanismen — so funktionieren sie</a>. Dieses Projekt wurde durch <b>Claude</b> möglich, das KI-Modell von Anthropic: das Uhrwerk, seine Prüfinstrumente und diese Seiten wurden in Zusammenarbeit mit ihm entworfen und gebaut. </div>',

  // ---- energy ----
  ['Wind a watch and you are bending steel. The mainspring is a long, thin ribbon coiled inside a drum: its outer end is riveted to the drum wall, its inner end is hooked to a shaft that stands still. Winding does not <em>rotate</em> the spring so much as change its <em>shape</em> — the same length of ribbon crowds into tight turns near the centre, and the energy of a wind is stored the way a drawn bow stores it, in elastic bending all along the ribbon\'s length.']:
    'Eine Uhr aufziehen heißt Stahl biegen. Die Zugfeder ist ein langes, dünnes Band, aufgerollt im Federhaus: ihr äußeres Ende ist an der Federhauswand vernietet, ihr inneres Ende an einem Federkern eingehängt, der stillsteht. Aufziehen <em>dreht</em> die Feder also weniger, als dass es ihre <em>Form</em> ändert — dieselbe Bandlänge drängt sich in enge Windungen nahe der Mitte, und die Energie eines Aufzugs steckt wie in einem gespannten Bogen in der elastischen Biegung über die ganze Bandlänge.',
  ['As the watch runs, the ribbon relaxes turn by turn and its stored energy flows out through the drum. One full wind here holds about <b>30 hours</b> of running, and the machinery spends it very slowly: the first wheel of the gear train makes one revolution every 17 1/7 hours — one and three-quarter turns over the whole reserve. Everything faster than that is gearing, which has its own entry below.']: 'Während die Uhr läuft, entspannt sich das Band Windung um Windung, und seine gespeicherte Energie fließt durch das Federhaus ab. Ein voller Aufzug trägt hier rund <b>30 Stunden</b> Gang, und das Werk gibt sie sehr langsam aus: das erste Rad des Räderwerks macht eine Umdrehung alle 17 1/7 Stunden — eindreiviertel Umdrehungen über die ganze Gangreserve. Alles Schnellere ist Übersetzung, die ihren eigenen Eintrag weiter unten hat.',
  ['Honesty note: the ribbon in the simulation is not a decoration. Its shape is recomputed as the wind changes, under two constraints a real spring obeys — neighbouring turns may touch but never merge, and every shape must be the same length of steel, because steel does not stretch. The picture of a wound spring bunched at the centre and a spent one spread against the wall is the geometry those two rules force.']:
    'Ehrlichkeitsnotiz: das Band in der Simulation ist keine Verzierung. Seine Form wird mit jedem Wickelzustand neu gerechnet, unter zwei Bedingungen, denen eine echte Feder gehorcht — benachbarte Windungen dürfen sich berühren, aber nie verschmelzen, und jede Form muss dieselbe Länge Stahl sein, denn Stahl dehnt sich nicht. Das Bild einer aufgezogenen Feder, die sich in der Mitte drängt, und einer abgelaufenen, die sich an der Wand ausbreitet, ist die Geometrie, die diese beiden Regeln erzwingen.',
  ['Where the energy comes from<span class="where">power</span>']: 'Woher die Energie kommt<span class="where">Kraft</span>',

  // ---- fusee ----
  ['A spring\'s pull is not constant: freshly wound it is strong, nearly spent it is weak. A timekeeper hates that, because the size of the push reaching the balance changes how it swings. The classical fix — this movement\'s namesake — is the <b>fusee</b>: a cone-shaped pulley connected to the spring\'s drum by a miniature chain — built like a bicycle chain, with links well under a millimetre long.']:
    'Der Zug einer Feder ist nicht konstant: frisch aufgezogen ist er stark, fast abgelaufen schwach. Einer Uhr behagt das nicht, denn die Größe des Antriebs, der die Unruh erreicht, ändert damit ihren Schwung. Die klassische Abhilfe — der Namensgeber dieses Werks — ist die <b>Schnecke</b>: eine kegelförmige Seilrolle, mit dem Federhaus durch eine winzige Kette verbunden — gebaut wie eine Fahrradkette, mit Gliedern deutlich unter einem Millimeter Länge.',
  ['The trick is leverage. Torque — turning force — is pull times lever arm. When the spring is strong, the chain pulls on the cone\'s <em>narrow</em> end: big pull, short lever. As the spring runs down, the chain walks along the cone\'s spiral groove toward the <em>wide</em> end: smaller pull, longer lever. The product, the torque handed to the gears, stays nearly level from full wind to empty.']:
    'Der Kniff ist die Hebelwirkung. Drehmoment — Drehkraft — ist Zug mal Hebelarm. Ist die Feder stark, zieht die Kette am <em>schmalen</em> Ende des Kegels: großer Zug, kurzer Hebel. Läuft die Feder ab, wandert die Kette in der spiraligen Rille zum <em>weiten</em> Ende: kleinerer Zug, längerer Hebel. Das Produkt, das an das Räderwerk abgegebene Drehmoment, bleibt nahezu gleich von vollem Aufzug bis leer.',
  ['The cone is cut against the spring\'s own measured decline, so the two curves cancel. The chain also explains the winding feel of such watches: winding spools the chain back from drum to cone, and a small detent keeps the gears driven during the seconds the wind would otherwise unload them.']:
    'Der Kegel ist gegen den gemessenen eigenen Abfall der Feder geschnitten, sodass sich die beiden Kurven aufheben. Die Kette erklärt auch das Aufzugsgefühl solcher Uhren: Aufziehen spult die Kette vom Federhaus zurück auf den Kegel, und eine kleine Sperrung hält das Räderwerk angetrieben, während der Aufzug es sonst kurz entlasten würde.',
  ['The fusee — evening out a dying spring<span class="where">power</span>']:
    'Die Schnecke — den Abfall einer sterbenden Feder ausgleichen<span class="where">Kraft</span>',
  ['Pull × lever arm ≈ constant']: 'Zug × Hebelarm ≈ konstant',
  ['PLATE 1']: 'TAFEL 1',
  ['freshly wound']: 'frisch aufgezogen',
  ['short lever']: 'kurzer Hebel',
  ['strong pull']: 'starker Zug',
  ['big pull × small radius']: 'großer Zug × kleiner Radius',
  ['nearly run down']: 'fast abgelaufen',
  ['long lever']: 'langer Hebel',
  ['weak pull']: 'schwacher Zug',
  ['small pull × big radius']: 'kleiner Zug × großer Radius',
  ['≈ the same torque']: '≈ dasselbe Drehmoment',
  // ---- fusee, plate 2 (§195 — the interactive bargain) ----
  ['Plate 2 puts that bargain under your finger. Drag the reserve from a full wind down to empty — or let it play — and watch the two quantities trade places while their product holds still. That level bar is the whole reason the cone exists.']:
    'Tafel 2 legt Ihnen diesen Handel unter den Finger. Ziehen Sie die Reserve vom vollen Aufzug bis leer — oder lassen Sie sie einfach laufen — und sehen Sie zu, wie die beiden Größen die Plätze tauschen, während ihr Produkt stillhält. Dieser waagerechte Balken ist der ganze Grund, aus dem der Kegel existiert.',
  ['The numbers are the machine\'s own, rounded: over the 30-hour reserve the spring\'s pull fades to about three-fifths of its full-wind strength, and the cone answers by letting the lever grow about 1.7× — so their product, the third bar, does not move. The fourth bar is the watch this would be without a fusee: every push to the balance sagging in step with the spring. One simplification is drawn: the pull fades along a straight line here, where the real spring\'s fade is a measured curve — which is why the real cone\'s flank is not quite straight either. It is cut against that curve, and the bargain holds exactly.']:
    'Die Zahlen sind die der Maschine selbst, gerundet: über die 30-Stunden-Reserve fällt der Zug der Feder auf etwa drei Fünftel seiner Stärke bei vollem Aufzug, und der Kegel antwortet, indem er den Hebel um etwa das 1,7-Fache wachsen lässt — sodass ihr Produkt, der dritte Balken, sich nicht bewegt. Der vierte Balken ist die Uhr, die dies ohne Schnecke wäre: jeder Antrieb zur Unruh sackt im Gleichschritt mit der Feder ab. Eine Vereinfachung ist gezeichnet: der Zug fällt hier entlang einer Geraden, während der Abfall der echten Feder eine gemessene Kurve ist — weshalb auch die Flanke des echten Kegels nicht ganz gerade ist. Sie ist gegen genau diese Kurve geschnitten, und der Handel geht exakt auf.',
  ['Run the bargain yourself']: 'Führen Sie den Handel selbst',
  ['PLATE 2']: 'TAFEL 2',
  ['fully wound · big pull, short lever']: 'voll aufgezogen · großer Zug, kurzer Hebel',
  ['run down · small pull, long lever']: 'abgelaufen · kleiner Zug, langer Hebel',
  ['the product is not moving']: 'das Produkt bewegt sich nicht',
  ['⏸ pause']: '⏸ Pause',
  ['▶ play']: '▶ Abspielen',
  ['the cone, side on']: 'der Kegel, von der Seite',
  ['wide end']: 'weites Ende',
  ['narrow end']: 'schmales Ende',
  ['the chain walks wide as the spring fades; the lever is the radius it pulls at']:
    'die Kette wandert ins Weite, wenn die Feder nachlässt; der Hebel ist der Radius, an dem sie zieht',
  ['the spring\'s pull']: 'der Zug der Feder',
  ['the lever arm']: 'der Hebelarm',
  ['pull × lever — what the gears feel']: 'Zug × Hebel — was das Räderwerk spürt',
  ['× 1.0']: '× 1,0',
  ['level']: 'konstant',
  ['if the chain pulled at one radius']: 'zöge die Kette an einem festen Radius',
  ['reserve']: 'Reserve',

  // ---- gears ----
  ['Everything between the drum and the ticking is multiplication. When a wheel with many teeth drives a small pinion, the pinion turns faster in exact proportion to the tooth counts — a wheel of 120 teeth driving a pinion of 7 turns it exactly 17 1/7 times per revolution, and there is nothing more to know. Speed is bought at the price of force, the same trade as a bicycle\'s gears.']: 'Alles zwischen dem Federhaus und dem Ticken ist Multiplikation. Treibt ein Rad mit vielen Zähnen ein kleines Trieb, dreht sich das Trieb genau im Verhältnis der Zähnezahlen schneller — ein Rad mit 120 Zähnen an einem Trieb mit 7 dreht dieses genau 17 1/7 Mal je Umdrehung, und mehr gibt es dazu nicht zu wissen. Geschwindigkeit wird mit Kraft bezahlt, derselbe Handel wie bei den Gängen eines Fahrrads.',
  ['Four such steps stand between the power and the escapement. The last three you can check on your fingers: 7½ × 8 × 10 = 600, which is exactly one turn per hour becoming one turn every 6 seconds. The first step is the odd fraction, × 17 1/7: the "great wheel", riding on the fusee cone itself, turns once in 17 1/7 hours, and its 120 teeth driving a 7-leaf pinion hand the centre wheel its once-per-hour turn. That gearing was chosen for the chain\'s sake — spreading the 30-hour reserve over fewer, wider-spaced turns of groove is what gives every link room to sit flat against the cone instead of perching on a corner.']: 'Vier solcher Stufen stehen zwischen der Kraft und der Hemmung. Die letzten drei können Sie an den Fingern nachrechnen: 7½ × 8 × 10 = 600, genau der Schritt von einer Umdrehung je Stunde zu einer Umdrehung alle 6 Sekunden. Die erste Stufe ist der krumme Bruch, × 17 1/7: das „Großbodenrad“, das auf dem Schneckenkegel selbst sitzt, dreht sich einmal in 17 1/7 Stunden, und seine 120 Zähne an einem 7-flügeligen Trieb geben dem Zentrumsrad seine Umdrehung je Stunde. Diese Übersetzung wurde der Kette zuliebe gewählt — die 30-Stunden-Reserve auf weniger, weiter auseinanderliegende Rillenwindungen zu verteilen ist es, was jedem Glied den Platz gibt, flach am Kegel anzuliegen, statt auf einer Ecke zu balancieren.',
  ['The hour hand is one more piece of the same arithmetic. A small gear turning with the minute hand drives a wheel three times its size, and a pinion on that wheel drives the hour wheel at 4:1 more — 3 × 4 = <b>12:1</b>, which is why the hour hand makes one circuit while the minute hand makes twelve. In this simulation that ratio is never written down anywhere: it emerges because those four tooth counts multiply to it, exactly as in the metal.']:
    'Der Stundenzeiger ist ein weiteres Stück derselben Rechnung. Ein kleines Rad, das mit dem Minutenzeiger läuft, treibt ein Rad von dreifacher Größe, und ein Trieb auf diesem Rad treibt das Stundenrad noch einmal mit 4:1 — 3 × 4 = <b>12:1</b>, weshalb der Stundenzeiger einen Umlauf macht, während der Minutenzeiger zwölf macht. In dieser Simulation steht dieses Verhältnis nirgends geschrieben: es entsteht, weil jene vier Zähnezahlen sich dazu multiplizieren, genau wie im Metall.',
  ['Two of the train\'s wheels double as the display: the centre wheel turns once an hour and carries the minute hand; the fourth wheel turns once a minute and carries the seconds hand. No hand is ever <em>told</em> where to point — its angle arrives through the teeth.']:
    'Zwei Räder des Räderwerks sind zugleich die Anzeige: das Minutenrad dreht sich einmal je Stunde und trägt den Minutenzeiger; das Sekundenrad dreht sich einmal je Minute und trägt den Sekundenzeiger. Keinem Zeiger wird je <em>gesagt</em>, wohin er zeigen soll — sein Winkel kommt durch die Zähne.',
  ['Gears are arithmetic<span class="where">power → display</span>']: 'Räderwerk ist Rechnen<span class="where">Kraft → Anzeige</span>',
  ['One turn in 17 1/7 hours becomes one turn in 6 seconds']: 'Eine Umdrehung in 17 1/7 Stunden wird zu einer in 6 Sekunden',
  ['great wheel · 120 teeth']: 'Großbodenrad · 120 Zähne',
  ['1 turn / 17 1/7 h']: '1 Umdr. / 17 1/7 h',
  ['× 17 1/7']: '× 17 1/7',
  ['× 8']: '× 8',
  ['centre wheel']: 'Minutenrad',
  ['1 turn / hour']: '1 Umdr. / Stunde',
  ['carries the minute hand']: 'trägt den Minutenzeiger',
  ['× 7½']: '× 7½',
  ['third wheel']: 'Kleinbodenrad',
  ['fourth wheel']: 'Sekundenrad',
  ['1 turn / minute']: '1 Umdr. / Minute',
  ['carries the seconds hand']: 'trägt den Sekundenzeiger',
  ['× 10']: '× 10',
  ['escape wheel']: 'Ankerrad',
  ['1 turn / 6 s']: '1 Umdr. / 6 s',

  // ---- escapement ----
  ['Left alone, the gear train would spin the whole reserve away in moments. The <b>escapement</b> is the checkout counter: it lets the train advance one fixed step at a time, and only when the timekeeper says so. Its three players are the escape wheel (the train\'s last, fastest wheel), a see-sawing lever with two jewelled pallet stones, and the balance — the swinging wheel of the next entry.']:
    'Sich selbst überlassen würde das Räderwerk die ganze Gangreserve in Augenblicken verdrehen. Die <b>Hemmung</b> ist die Kasse: sie lässt das Räderwerk um jeweils einen festen Schritt vorrücken, und nur dann, wenn der Zeitmesser es sagt. Ihre drei Mitspieler sind das Ankerrad (das letzte, schnellste Rad des Werks), ein wippender Anker mit zwei Rubinpaletten und die Unruh — das schwingende Rad des nächsten Eintrags.',
  ['Most of the time the escape wheel is simply <em>held</em>: a tooth presses on a stone, and the geometry of the stone\'s face is angled so that the pressure locks it tighter rather than slipping — like a door wedge that a push only seats deeper. When the swinging balance flicks the lever, the stone lifts, the wheel escapes forward by <b>12°</b> — half a tooth spacing, no more, because the lever\'s other stone is already in the way — and in that brief slide the tooth\'s tip rides across the stone\'s inclined end, pushing the stone out of its way and handing the balance a small shove that pays back what friction and air took from its swing. The end of each stone is cut on a slant that leans <em>toward</em> the wheel, so the tooth climbs it rather than falling off it. Then the wheel is caught again, and waits.']: 'Meist wird das Ankerrad schlicht <em>gehalten</em>: ein Zahn drückt auf eine Palette, und die Fläche der Palette ist so geneigt, dass der Druck sie fester sperrt statt sie rutschen zu lassen — wie ein Türkeil, den ein Stoß nur tiefer setzt. Wenn die schwingende Unruh den Anker anstößt, hebt die Palette ab, das Rad entkommt um <b>12°</b> nach vorn — eine halbe Zahnteilung, nicht mehr, weil die andere Palette schon wartet — und in diesem kurzen Gleiten läuft die Zahnspitze über das schräge Ende der Palette, schiebt die Palette aus dem Weg und gibt der Unruh einen kleinen Stoß, der ihr zurückzahlt, was Reibung und Luft ihrem Schwung genommen haben. Das Ende jeder Palette ist schräg geschnitten, und die Schräge neigt sich <em>zum</em> Rad hin, sodass der Zahn sie hinaufläuft statt von ihr abzufallen. Dann wird das Rad wieder gefangen und wartet.',
  ['That cycle is the tick: <b>5 per second</b> here, 18,000 per hour, each one an unlock–slide–catch. The wheel is in motion for only about a sixth of each beat — a watch is a machine that is almost always standing still.']:
    'Dieser Ablauf ist das Ticken: hier <b>5 je Sekunde</b>, 18.000 je Stunde, jedes ein Entsperren–Gleiten–Fangen. Das Rad ist nur etwa ein Sechstel jedes Schlages in Bewegung — eine Uhr ist eine Maschine, die fast immer stillsteht.',
  ['Two ideas travel through one contact, in opposite directions. Energy flows outward: train → wheel → stone → lever → balance, a shove per beat. Position flows inward: the wheel stands where the stones allow, so the balance — not the spring in the drum — decides what time it is.']:
    'Zwei Gedanken laufen durch denselben Kontakt, in entgegengesetzte Richtungen. Energie fließt nach außen: Räderwerk → Rad → Palette → Anker → Unruh, ein Stoß je Schlag. Die Stellung läuft nach innen: das Rad steht dort, wo die Paletten es zulassen, also entscheidet die Unruh — nicht die Feder im Federhaus —, wie spät es ist.',
  ['The escapement — spending energy five clicks a second<span class="where">timekeeping</span>']:
    'Die Hemmung — Energie ausgeben, fünf Klicks je Sekunde<span class="where">Zeitmessung</span>',
  ['Held, then let go — one step at a time']: 'Gehalten, dann losgelassen — Schritt für Schritt',
  ['locked — most of the beat']: 'gesperrt — der größte Teil des Schlags',
  ['stone holds the tooth']: 'Palette hält den Zahn',
  ['pressure seats it deeper']: 'Druck setzt sie tiefer',
  ['the train pushes; nothing moves']: 'das Werk drückt; nichts bewegt sich',
  ['impulse — a sixth of the beat']: 'Antrieb — ein Sechstel des Schlags',
  ['tooth shoves the stone,']: 'Zahn stößt die Palette,',
  ['flicking lever + balance']: 'Anker + Unruh folgen',
  ['the wheel advances 12° and is caught']: 'das Rad rückt 12° vor und wird gefangen',

  // ---- balance ----
  ['The timekeeper itself is the <b>balance</b>: a weighted rim on pivots, with a spiralled hairspring that twists as the rim turns and pushes it back toward centre. Twist it further, and the spring pushes back harder — restoring torque proportional to angle. Newton\'s law for rotation then gives the balance\'s angular acceleration as spring stiffness over rotational inertia, times the angle — and that equation is the same one a mass on a spring obeys. Its solution is a steady oscillation whose frequency depends on exactly two things: the <em>stiffness</em> of the spring and the <em>inertia</em> of the wheel. Frequency is the square root of stiffness over inertia — and nothing else.']:
    'Der Zeitmesser selbst ist die <b>Unruh</b>: ein beschwerter Reif auf Zapfen, mit einer spiralig gewundenen Spirale, die sich mit dem Reif verdreht und ihn zur Mitte zurückdrückt. Verdreht man weiter, drückt die Spirale stärker zurück — Rückstellmoment proportional zum Winkel. Newtons Gesetz für die Drehung gibt dann die Winkelbeschleunigung der Unruh als Federsteifigkeit geteilt durch Trägheitsmoment, mal dem Winkel — und das ist dieselbe Gleichung, der eine Masse an einer Feder gehorcht. Ihre Lösung ist eine gleichmäßige Schwingung, deren Frequenz von genau zwei Dingen abhängt: der <em>Steifigkeit</em> der Spirale und der <em>Trägheit</em> des Rades. Die Frequenz ist die Wurzel aus Steifigkeit durch Trägheit — und aus sonst nichts.',
  ['The remarkable consequence: the <em>amplitude is not in the formula</em>. Swing the balance wide or barely at all and each swing takes the same time — a big swing moves faster through a longer arc, and the two effects cancel. That property, called <b>isochronism</b>, is why a watch can keep time while its mainspring\'s push (and so its balance\'s swing) sags across 30 hours. Galileo noticed it in a swinging lamp; every mechanical watch since is a bet placed on it.']:
    'Die bemerkenswerte Folge: die <em>Amplitude steht nicht in der Formel</em>. Lassen Sie die Unruh weit oder kaum schwingen — jede Schwingung dauert gleich lang, denn ein weiter Ausschlag läuft schneller durch einen längeren Bogen, und beides hebt sich auf. Diese Eigenschaft, <b>Isochronismus</b> genannt, ist der Grund, weshalb eine Uhr Zeit halten kann, während der Antrieb ihrer Zugfeder (und damit der Ausschlag ihrer Unruh) über 30 Stunden nachlässt. Galilei bemerkte sie an einer schwingenden Lampe; jede mechanische Uhr seither ist eine Wette darauf.',
  ['The physics also says how to <em>adjust</em> such a watch. This balance is "free-sprung": nothing ever pinches or shortens the hairspring. Instead the rim carries threaded timing screws — screw a pair inward and the rim\'s mass moves toward the axis, the inertia drops, and the watch runs faster; outward, slower. Rate lives in the denominator of that square root.']:
    'Die Physik sagt auch, wie man eine solche Uhr <em>reguliert</em>. Diese Unruh ist „frei schwingend“: nichts klemmt oder verkürzt je die Spirale. Stattdessen trägt der Reif eingeschraubte Regulierschrauben — dreht man ein Paar hinein, wandert Masse des Reifs zur Achse, die Trägheit sinkt und die Uhr geht vor; heraus, nach. Der Gang sitzt im Nenner jener Wurzel.',
  ['Honesty note: in this simulation the spring is real arithmetic, not a prop. The wheel\'s inertia is computed from its drawn dimensions — about 85% of it in the rim, a tenth in the screws, the rest in the arms — and the hairspring\'s cross-section is then <em>solved</em> so that the square root lands exactly on the advertised rate. The ribbon that comes out of the solve is about 0.024 mm thick, inside the 0.02–0.04 mm range real hairspring stock is drawn in. The one liberty is the drawn amplitude, above.']:
    'Ehrlichkeitsnotiz: in dieser Simulation ist die Spirale echte Rechnung, keine Attrappe. Die Trägheit des Rades wird aus seinen gezeichneten Abmessungen gewogen — etwa 85 % davon im Reif, ein Zehntel in den Schrauben, der Rest in den Armen — und der <em>Querschnitt</em> der Spirale wird dann so gelöst, dass die Wurzel genau auf der angegebenen Frequenz landet. Das Band, das aus dieser Lösung kommt, ist rund 0,024 mm dick und liegt damit im Bereich 0,02–0,04 mm, in dem echtes Spiralfederband gezogen wird. Die eine Freiheit ist die gezeichnete Amplitude, siehe oben.',
  ['Here the balance completes 2½ full oscillations per second, and each oscillation crosses the escapement twice — once each way — giving the 5 ticks per second of the previous entry. A healthy real balance swings roughly three-quarters of a turn each way; on screen the swing is drawn smaller than life so the beat stays readable at a glance.']:
    'Hier vollführt die Unruh 2½ volle Schwingungen je Sekunde, und jede Schwingung quert die Hemmung zweimal — je Richtung einmal —, was die 5 Ticks je Sekunde des vorigen Eintrags ergibt. Eine gesunde echte Unruh schwingt etwa drei Viertel einer Umdrehung je Seite; auf dem Schirm ist der Ausschlag kleiner gezeichnet als in Wirklichkeit, damit der Schlag auf einen Blick lesbar bleibt.',
  ['Why the balance keeps time<span class="where">timekeeping</span>']: 'Warum die Unruh die Zeit hält<span class="where">Zeitmessung</span>',
  ['Big swing or small — the same time per swing']: 'Weit oder eng — dieselbe Zeit je Schwingung',
  ['wide swing']: 'weiter Ausschlag',
  ['long arc, high speed']: 'langer Bogen, hohe Geschwindigkeit',
  ['narrow swing']: 'enger Ausschlag',
  ['short arc, low speed']: 'kurzer Bogen, geringe Geschwindigkeit',
  ['same period —']: 'gleiche Dauer —',
  ['2½ swings per second']: '2½ Schwingungen je Sekunde',

  ['A flat spiral does not quite pay that bet, and watchmakers have known it since Breguet. The spring\'s outer end is clamped to a fixed post, so the coils do not breathe evenly about the centre as they wind and unwind: the spring\'s centre of mass sits a little off the pivot axis — here about a tenth of a millimetre — and shifts as the spring breathes. The spring then leans sideways on the pivots, by a different amount at every amplitude. That is a rate error which varies with how far the balance swings — precisely the error isochronism was supposed to remove.']: 'Eine flache Spirale löst dieses Versprechen nicht ganz ein, und Uhrmacher wissen das seit Breguet. Das äußere Ende der Spirale ist an einem festen Klötzchen eingespannt, deshalb atmen die Windungen beim Auf- und Abwickeln nicht gleichmäßig um die Mitte: der Schwerpunkt der Spirale liegt ein wenig neben der Zapfenachse — hier etwa ein Zehntelmillimeter — und wandert, während die Spirale atmet. Die Spirale drückt dann seitlich gegen die Zapfen, bei jeder Amplitude unterschiedlich stark. Das ist ein Gangfehler, der davon abhängt, wie weit die Unruh ausschlägt — genau der Fehler, den der Isochronismus beseitigen sollte.',
  ['The classical answer is the <b>overcoil</b>, Breguet\'s. Lift the last three-quarters of a turn clear of the body — here by under a third of a millimetre, barely more than the ribbon is tall — and curve it back <em>inward</em>, so the spring finishes above its own coils instead of out beside them. Get that curve right and the centre of mass lands on the pivot axis: the coils breathe concentrically, and the sideways lean nearly vanishes. This balance carries one. Its curve is not drawn by hand but <em>solved</em> — for the centre of mass landing on the axis, for the end coming to rest over the body of the spring rather than outside it, and for a bend no tighter than the one the ribbon already takes where it grips the staff.']: 'Die klassische Antwort ist die <b>Endkurve</b>, Breguets. Man hebt die letzte Dreivierteldrehung über den Körper der Spirale — hier um weniger als ein Drittel Millimeter, kaum mehr als das Band hoch ist — und biegt sie wieder nach <em>innen</em>, sodass die Spirale über ihren eigenen Windungen endet statt daneben. Trifft man diese Kurve richtig, landet der Schwerpunkt auf der Zapfenachse: die Windungen atmen konzentrisch, und der seitliche Druck verschwindet nahezu. Diese Unruh trägt eine solche Kurve. Gezeichnet ist sie nicht von Hand, sondern <em>gelöst</em> — darauf, dass der Schwerpunkt auf der Achse liegt, dass das Ende über dem Körper der Spirale zur Ruhe kommt statt außerhalb, und dass keine Biegung enger ausfällt als die, die das Band ohnehin dort nimmt, wo es die Welle umfasst.',
  ['The raised curve is the shape the solve produced, traced at the scale of the drawing; the flat spiral beside it is schematic. Measured on this spring, at the swing drawn on screen, adding the terminal curve takes the sideways push on the pivots from about 4.7 to about 0.20 millionths of a newton — a factor of about 24. At a real three-quarter-turn swing a residue survives, because the rule the curve is solved against is a small-swing statement: there the factor is about 6 rather than 24, and this page reports that rather than rounding it away. The centre-of-mass marks are drawn far larger than life, as the swing was in the previous plate — the real offset is about a tenth of a millimetre on a spring some 6 mm across.']: 'Die angehobene Kurve ist die Form, die der Solver ergeben hat, im Maßstab der Zeichnung nachgezogen; die flache Spirale daneben ist schematisch. An dieser Spirale gemessen, beim auf dem Bildschirm gezeichneten Ausschlag, senkt die Endkurve den seitlichen Druck auf die Zapfen von etwa 4,7 auf etwa 0,20 Millionstel Newton — um einen Faktor von rund 24. Bei einem echten Dreiviertelausschlag bleibt ein Rest, denn die Regel, gegen die die Kurve gelöst wird, gilt für kleine Ausschläge: dort beträgt der Faktor etwa 6 statt 24, und diese Seite nennt das, statt es wegzurunden. Die Schwerpunktmarken sind weit größer als in Wirklichkeit gezeichnet, wie der Ausschlag auf der vorigen Tafel — der echte Versatz beträgt etwa ein Zehntelmillimeter bei einer Spirale von rund 6 mm Durchmesser.',
  ['Lifted clear, curved back inside']: 'Abgehoben, nach innen zurückgeführt',
  ['flat spiral']: 'flache Spirale',
  ['with the overcoil']: 'mit Endkurve',
  ['centre of mass off the axis']: 'Schwerpunkt neben der Achse',
  ['centre of mass on the axis']: 'Schwerpunkt auf der Achse',
  ['the spring leans on the pivots']: 'die Spirale drückt auf die Zapfen',
  ['the lean nearly vanishes']: 'der Druck verschwindet fast',

  // ---- keyless ----
  ['The crown at the movement\'s edge does two unrelated things — winds the spring, sets the hands — and the mechanism that decides which is a small axial clutch on the crown\'s stem. Pushed home, the stem\'s gear engages the winding path: each turn of the crown spools chain back onto the fusee cone, storing energy. Pulled out one stop, a pivoting lever slides that gear a couple of millimetres along the stem into the setting path, where it reaches the hand wheels instead.']:
    'Die Krone am Rand des Werks tut zwei ganz verschiedene Dinge — die Feder aufziehen, die Zeiger stellen — und was gerade gilt, entscheidet eine kleine axiale Kupplung auf der Aufzugswelle. Eingedrückt greift das Trieb der Welle in den Aufzugsweg: jede Drehung der Krone spult Kette zurück auf den Schneckenkegel und speichert Energie. Eine Raste herausgezogen, schiebt ein schwenkender Hebel dasselbe Trieb ein paar Millimeter längs der Welle in den Stellweg, wo es stattdessen das Zeigerwerk erreicht.',
  ['Turn the crown the wrong way and nothing is lost: a saw-toothed clutch face rides over its mate with a soft snap per tooth, and a small spring drops it back in — the guard every real stem carries, so a backward turn can never unwind the spring.']: 'Dreht man die Krone falsch herum, geht nichts verloren: eine sägeverzahnte Kupplungsfläche gleitet mit einem weichen Schnappen je Zahn über ihr Gegenstück, und eine kleine Feder setzt sie wieder ein — die Sicherung, die jede echte Aufzugwelle trägt, damit eine Rückwärtsdrehung die Feder nie entspannen kann.',
  ['One crown, two jobs<span class="where">interface</span>']: 'Eine Krone, zwei Aufgaben<span class="where">Bedienung</span>',

  // ---- alarm ----
  ['This movement carries a complete second power system for its alarm, with its own crown, its own barrel-spring, and its own release. The alarm crown does for the alarm what the main crown does for the time: turned one way it sets a disc under the dial to the chosen alarm time (a central alarm hand shows it, riding beneath the hour hand); pushed home it winds the alarm\'s own spring.']:
    'Dieses Werk trägt ein vollständiges zweites Kraftsystem für seinen Wecker, mit eigener Krone, eigener Weckerfeder und eigener Auslösung. Die Weckerkrone tut für den Wecker, was die Hauptkrone für die Zeit tut: in die eine Richtung gedreht stellt sie eine Scheibe unter dem Zifferblatt auf die gewählte Weckzeit (ein zentraler Weckzeiger zeigt sie an und läuft unter dem Stundenzeiger); eingedrückt zieht sie die eigene Feder des Weckers auf.',
  ['The release is a mechanical comparison, made by touch. A spring-loaded finger — the <b>feeler</b> — rests against the edge of the rotating alarm disc, which turns with the hours. The disc\'s edge carries a notch at the set time; everywhere else the feeler rides the high rim and the alarm stays blocked. When the dial\'s time reaches the set time, the notch arrives under the feeler, the feeler drops in, and the block is withdrawn: the alarm spring is free to run. It spins a small train that swings a hammer against a gong, and rings until the spring is spent — or until a pull of the alarm crown lifts the feeler out and parks it.']:
    'Die Auslösung ist ein mechanischer Vergleich, ertastet. Ein gefederter Finger — der <b>Fühlhebel</b> — liegt am Rand der umlaufenden Weckerscheibe an, die mit den Stunden dreht. Der Rand der Scheibe trägt an der eingestellten Zeit eine Kerbe; überall sonst läuft der Fühlhebel auf dem hohen Rand und der Wecker bleibt gesperrt. Erreicht die Zeit des Zifferblatts die eingestellte Zeit, kommt die Kerbe unter den Fühlhebel, er fällt ein, und die Sperre ist weg: die Weckerfeder darf laufen. Sie treibt ein kleines Räderwerk, das einen Hammer gegen die Gongfeder schwingt, und schlägt, bis die Feder erschöpft ist — oder bis ein Zug an der Weckerkrone den Fühlhebel aushebt und parkt.',
  ['Arming is its own little machine: pressing the pusher ratchets a star-shaped column wheel round one tooth per press, alternately enabling and disabling the release — the same switch-by-column that chronograph buttons use.']:
    'Das Scharfstellen ist eine eigene kleine Maschine: ein Druck auf den Drücker schaltet ein sternförmiges Schaltrad um je einen Zahn weiter und gibt die Auslösung abwechselnd frei und sperrt sie — dieselbe Umschaltung über ein Schaltrad, die auch Chronographendrücker verwenden.',
  // ---- §104: the ringing is driven now ----
  ['The alarm — a second spring with a voice<span class="where">alarm</span>']: 'Der Wecker — eine zweite Feder mit Stimme<span class="where">Wecker</span>',

  // ---- gong ----
  ['The alarm\'s voice is a steel bar clamped at one end — a stiff one-sided beam the hammer strikes near its foot. Strike any such bar and it rings at several frequencies at once: the fundamental, plus overtones whose positions are fixed by the physics of a bending beam, not by any tuner. For a clamped-free bar the second mode lands at about <b>6.3×</b> the fundamental — not 2×, not 3×, nothing on the musical ladder. Overtones that miss the whole-number rungs are what your ear calls "metallic"; a guitar string\'s overtones land exactly on them, which is why a string is a note and a struck bar is a <em>clang</em>.']:
    'Die Stimme des Weckers ist ein an einem Ende eingespannter Stahlstab — ein steifer einseitiger Balken, den der Hammer nahe seinem Fuß trifft. Schlägt man einen solchen Stab an, klingt er in mehreren Frequenzen zugleich: dem Grundton, dazu Obertöne, deren Lage die Physik eines biegenden Balkens festlegt, kein Stimmer. Bei einem einseitig eingespannten Stab liegt die zweite Eigenform bei etwa dem <b>6,3fachen</b> des Grundtons — nicht 2×, nicht 3×, auf keiner Sprosse der musikalischen Leiter. Obertöne, die die ganzzahligen Sprossen verfehlen, sind das, was Ihr Ohr „metallisch“ nennt; die Obertöne einer Gitarrensaite treffen sie genau, weshalb eine Saite ein Ton ist und ein angeschlagener Stab ein <em>Scheppern</em>.',
  ['Why the gong sounds like metal, not music<span class="where">alarm</span>']:
    'Warum der Gong nach Metall klingt und nicht nach Musik<span class="where">Wecker</span>',

  // ---- honesty ----
  ['This project polices its own language, and the primer is bound by the same rule as everything else. Two words are used precisely. <b>Modelled</b> means <em>described</em>: the geometry exists, its dimensions are derived from stated constraints, and instruments check the description for contradictions. <b>Simulated</b> means <em>driven</em>: the part moves because another part pushes it, cause to effect through real contacts — not because an animation poses it where the answer should be.']:
    'Dieses Projekt achtet auf seine eigene Sprache, und die Einführung ist an dieselbe Regel gebunden wie alles andere. Zwei Wörter werden genau verwendet. <b>Modelliert</b> heißt <em>beschrieben</em>: die Geometrie existiert, ihre Maße sind aus genannten Randbedingungen abgeleitet, und Instrumente prüfen die Beschreibung auf Widersprüche. <b>Simuliert</b> heißt <em>getrieben</em>: das Teil bewegt sich, weil ein anderes Teil es schiebt, Ursache zu Wirkung über echte Kontakte — nicht weil eine Animation es dorthin setzt, wo die Antwort sein sollte.',
  ['If a claim on this page overstates what the machine underneath actually does, that is a bug in this page — the ledger, not the prose, is the record.']:
    'Behauptet diese Seite mehr, als die Maschine darunter wirklich tut, dann ist das ein Fehler dieser Seite — das Verzeichnis ist die Aufzeichnung, nicht der Text.',
  ['What this simulation claims — and what it doesn\'t<span class="where">the rules</span>']:
    'Was diese Simulation behauptet — und was nicht<span class="where">die Regeln</span>',
  // TODO 131 — the escapement's plate 2 and the slant that carries the impulse.
  ['Plate 2 slows one beat down to a few seconds and draws it from the lever\'s point of view, so the stones stand still and the wheel does the moving. Watch the right stone: the tooth\'s tip sits on its corner, slides down its slanted end as the stone lifts, and drops off — and the next tooth is already landing on the left stone\'s corner.']: 'Tafel 2 dehnt eine Halbschwingung auf ein paar Sekunden und zeichnet sie aus der Sicht des Ankers, sodass die Paletten stillstehen und das Rad sich bewegt. Achten Sie auf die rechte Palette: die Zahnspitze sitzt auf ihrer Kante, gleitet ihr schräges Ende hinab, während die Palette abhebt, und fällt ab — und der nächste Zahn landet schon auf der Kante der linken Palette.',
  ['What the slant buys. The stone\'s end is cut so that the tooth\'s tip, travelling forward while the stone lifts, stays pressed on it for almost the whole step — the wheel only runs free for the last degree and a half before the other stone catches it. Cut the slant the other way and the tip would leave the corner into thin air, the wheel would spin the whole step unloaded, and the balance would get nothing. Two things here are honest simplifications: the lever\'s swing is drawn as the simulation poses it, and the little backward twitch of the wheel at the start of each beat is a posed gesture rather than a measured recoil.']: 'Was die Schräge kauft. Das Ende der Palette ist so geschnitten, dass die Zahnspitze, die vorwärts läuft, während die Palette abhebt, fast den ganzen Schritt lang an ihr anliegt — das Rad läuft nur die letzten anderthalb Grad frei, bevor die andere Palette es fängt. Schneidet man die Schräge andersherum, verließe die Spitze die Kante ins Leere, das Rad drehte den ganzen Schritt unbelastet, und die Unruh bekäme nichts. Zwei Dinge hier sind ehrliche Vereinfachungen: der Ausschlag des Ankers ist gezeichnet, wie die Simulation ihn stellt, und das kleine Rückwärtszucken des Rades zu Beginn jeder Halbschwingung ist eine gestellte Geste, kein gemessener Rückprall.',
  ['One beat, slowed down']: 'Eine Halbschwingung, verlangsamt',
  ['unlock · the stone lifts, the wheel twitches back']: 'Entriegeln · die Palette hebt ab, das Rad zuckt zurück',
  ['the stone about to catch']: 'die Palette, die gleich fängt',
  ['the stone letting go']: 'die Palette, die loslässt',
  ['the lever\'s frame, in the machine\'s proportions: stones still, wheel moving; the dot is a touch']: 'Ankerrahmen, in Maschinenproportion: Paletten still, Rad bewegt; der Punkt ist eine Berührung',
  ['beat']: 'Halbschwingung',
  ['locked · the stone holds the wheel']: 'gesperrt · die Palette hält das Rad',
  ['impulse · the tip rides the slant']: 'Impuls · die Spitze läuft die Schräge entlang',
  ['drop · the wheel runs free to the other stone']: 'Fall · das Rad läuft frei bis zur anderen Palette',

  // §223 — German: the keys this table was still missing, re-priced with the
  // checker's own isInvariant (bare constants were never gaps).
  ['Setting the hands turns the <em>same</em> wheels the train drives — the 12:1 arithmetic of the gears entry is driven backwards from the crown, so a set hand and a running hand are the same hand at the same angle. Pulling the crown also brakes the balance ("hacking"): a sprung pad rises against the <em>underside</em> of the balance rim — not its edge, where the timing screws of the previous entry stand proud all the way round — and holds the wheel still, so the watch can be synchronised to a signal. Push the crown home and the balance is released to swing again.']: 'Das Stellen der Zeiger dreht <em>dieselben</em> Räder, die das Räderwerk antreibt — die 12:1-Arithmetik aus dem Eintrag über die Zahnräder wird von der Krone aus rückwärts angetrieben, ein gestellter und ein laufender Zeiger sind also derselbe Zeiger im selben Winkel. Das Ziehen der Krone bremst außerdem die Unruh („Sekundenstopp“): ein gefedertes Kissen hebt sich gegen die <em>Unterseite</em> des Unruhreifs — nicht gegen seine Kante, wo die Regulierschrauben des vorigen Eintrags rundum hervorstehen — und hält das Rad still, sodass die Uhr auf ein Signal synchronisiert werden kann. Drückt man die Krone hinein, wird die Unruh freigegeben und schwingt wieder.',
  ['The same pull does something the eye notices first: the seconds hand does not stop where it stands, it flies back to zero. That is a second mechanism, borrowed from the stopwatch. The seconds hand does not ride the train\'s wheel directly but a companion shaft gripped to it by friction, and on that shaft sits a heart-shaped cam — a spiral whose radius falls all the way round to a single lowest point. Pulling the crown drops a spring-loaded hammer onto the cam\'s edge, and here the shape does the thinking: pressing anywhere on a falling spiral produces a turning force toward the low point, so the cam rolls under the hammer until the hammer seats in the notch — wherever it started from. The notch is cut at the display\'s zero, the friction grip pays for the jump, and the gear train behind it never feels a thing: it keeps its own count of the time while the display is snapped back. Set the watch against a signal, push the crown home, and the seconds begin from zero instead of from wherever they happened to be.']: 'Derselbe Zug tut etwas, das dem Auge zuerst auffällt: der Sekundenzeiger bleibt nicht stehen, wo er steht, er springt auf null zurück. Das ist ein zweiter Mechanismus, von der Stoppuhr entlehnt. Der Sekundenzeiger sitzt nicht direkt auf dem Rad des Räderwerks, sondern auf einer Begleitwelle, die es durch Reibung festhält, und auf dieser Welle sitzt ein herzförmiger Nocken — eine Spirale, deren Radius rundherum bis zu einem einzigen tiefsten Punkt abfällt. Das Ziehen der Krone lässt einen gefederten Hammer auf die Kante des Nockens fallen, und hier denkt die Form: ein Druck irgendwo auf eine abfallende Spirale erzeugt eine Drehkraft zum tiefsten Punkt hin, also rollt der Nocken unter dem Hammer, bis der Hammer in der Kerbe sitzt — ganz gleich, wo er begann. Die Kerbe ist bei der Null der Anzeige geschnitten, die Reibkupplung bezahlt den Sprung, und das Räderwerk dahinter spürt nichts: es zählt die Zeit weiter für sich, während die Anzeige zurückschnappt. Stellen Sie die Uhr nach einem Signal, drücken Sie die Krone hinein, und die Sekunden beginnen bei null statt dort, wo sie gerade standen.',
  ['Honesty note, both directions. The arming chain is genuinely <em>driven</em>: the press moves the pawl, the pawl indexes the column, and every part downstream stands where the surface pushing it puts it — the simulation measures every one of those contacts closed on every test run. The ringing now is too: the hammer\'s <em>tempo</em> is derived from the spring\'s torque through the speed limiter real alarms use — a small anchor fluttering on a toothed wheel, its balancing ring sized by arithmetic — so the bell starts brisk on a full spring and audibly slows as it spends, stopping at a floor the spring\'s pre-tension sets instead of trailing off. What the debt list still records here: the hammer\'s own fall is timed from the strike schedule, not from its spring — and the entry is sharper now than it was. The spring in the drawing turns out to change LENGTH as the hammer swings, by about a third of itself, which no steel blade does; and a blade that would give the fall its timing honestly would have to be eighteen millimetres long inside a thirty-two millimetre movement. The answer is a coiled spring on the hammer\'s own arbor, and the ledger now carries what it is worth: about twenty-six decibels of the alarm\'s loudness.']: 'Ehrlichkeitsvermerk, in beide Richtungen. Die Spannkette wird wirklich <em>angetrieben</em>: der Druck bewegt die Klinke, die Klinke schaltet die Säule weiter, und jedes Teil dahinter steht dort, wo die Fläche, die es schiebt, es hinstellt — die Simulation misst jeden dieser Kontakte bei jedem Testlauf als geschlossen. Das Läuten nun auch: das <em>Tempo</em> des Hammers ist aus dem Drehmoment der Feder abgeleitet, über den Geschwindigkeitsbegrenzer, den echte Wecker verwenden — ein kleiner Anker, der auf einem Zahnrad flattert, sein Ausgleichsring rechnerisch bemessen —, sodass die Glocke bei voller Feder flott beginnt und hörbar langsamer wird, während sie sich verausgabt, und an einer Untergrenze stoppt, die die Vorspannung der Feder setzt, statt auszuklingen. Was die Schuldenliste hier noch verzeichnet: der Fall des Hammers selbst ist aus dem Schlagplan getaktet, nicht aus seiner Feder — und der Eintrag ist jetzt schärfer als zuvor. Die Feder in der Zeichnung ändert beim Schwingen des Hammers ihre LÄNGE, um etwa ein Drittel ihrer selbst, was keine Stahlblattfeder tut; und eine Blattfeder, die dem Fall ehrlich sein Timing gäbe, müsste in einem Werk von zweiunddreißig Millimetern achtzehn Millimeter lang sein. Die Antwort ist eine gewickelte Feder auf der eigenen Welle des Hammers, und die Bilanz führt jetzt, was sie wert ist: etwa sechsundzwanzig Dezibel der Lautstärke des Weckers.',
  ['In the simulation the sound is synthesised from the drawn bar itself: its length and thickness set the fundamental, the beam equation sets the overtone ratios, and shortening the bar raises every partial together — exactly as filing a real gong would. Nothing about the sound is a recording, and no frequency is picked by hand. Which of the two partials you mostly hear is arithmetic too: a bar this short pushes air feebly at low frequencies and far better at high ones, so the overtone carries the ring and the fundamental sits a long way beneath it.']: 'In der Simulation wird der Klang aus dem gezeichneten Stab selbst synthetisiert: seine Länge und Dicke setzen den Grundton, die Balkengleichung setzt die Obertonverhältnisse, und das Kürzen des Stabs hebt alle Teiltöne gemeinsam an — genau wie das Feilen einer echten Tonfeder. Nichts am Klang ist eine Aufnahme, und keine Frequenz ist von Hand gewählt. Welchen der beiden Teiltöne man überwiegend hört, ist ebenfalls Arithmetik: ein so kurzer Stab bewegt bei tiefen Frequenzen die Luft kaum und bei hohen weit besser, also trägt der Oberton den Klang, und der Grundton liegt weit darunter.',
  ['How LOUD a bare wire can be is the more sobering question, and the simulation now answers it. A wire is a string with no soundboard: it displaces almost no air, so a gong of this size radiates a startlingly small part of the blow. The wire was a third of a millimetre thick because nothing had ever sized it; giving it the room it actually has above the plate takes it to a millimetre, and the hammer head grows into the same room, which together are worth about eighteen decibels — from below the threshold of hearing to a faint but real sound at arm\'s length.']: 'Wie LAUT ein bloßer Draht sein kann, ist die ernüchterndere Frage, und die Simulation beantwortet sie jetzt. Ein Draht ist eine Saite ohne Resonanzboden: er verdrängt kaum Luft, also strahlt eine Tonfeder dieser Größe einen verblüffend kleinen Teil des Schlags ab. Der Draht war ein Drittel Millimeter dick, weil ihn nie etwas bemessen hatte; ihm den Raum zu geben, den er über der Platine tatsächlich hat, bringt ihn auf einen Millimeter, und der Hammerkopf wächst in denselben Raum, was zusammen etwa achtzehn Dezibel wert ist — von unter der Hörschwelle zu einem leisen, aber echten Klang auf Armlänge.',
  ['The ring has since left the plate altogether. On the plate its note was fixed not by the ear but by where a foot could be screwed down — the balance\'s opening left two stations, and the nearer one forced a bar half again as long as the ear wants. In the empty channel between the plate\'s rim and the case there is no opening anywhere, so the bar is now exactly the length that puts its note where hearing is keenest, and the hammer head is sized to the wire rather than to the room. The price was one more part: a hammer standing out at the ring can no longer reach the striking wheel, so a small lever of two equal arms carries the lift across, and the hammer, its blow and its lever are all drawn and measured like everything else. Worth about ten decibels on top of the eighteen — still faint, and still a floor.']: 'Der Ring hat die Platine inzwischen ganz verlassen. Auf der Platine war sein Ton nicht vom Ohr festgelegt, sondern davon, wo sich ein Fuß anschrauben ließ — die Öffnung der Unruh ließ zwei Stationen übrig, und die nähere erzwang einen Stab, der anderthalbmal so lang war, wie das Ohr ihn will. Im leeren Kanal zwischen dem Rand der Platine und dem Gehäuse gibt es nirgends eine Öffnung, also hat der Stab jetzt genau die Länge, die seinen Ton dorthin legt, wo das Gehör am schärfsten ist, und der Hammerkopf ist nach dem Draht bemessen statt nach dem Raum. Der Preis war ein weiteres Teil: ein Hammer, der draußen am Ring steht, erreicht das Schlagrad nicht mehr, also trägt ein kleiner Hebel mit zwei gleichen Armen den Hub hinüber, und Hammer, Schlag und Hebel sind alle gezeichnet und gemessen wie alles andere. Etwa zehn Dezibel wert, zusätzlich zu den achtzehn — immer noch leise, und immer noch eine Untergrenze.',
  ['Honesty note. That figure is the wire radiating on its own, and it is a floor rather than a prediction of the watch — for two reasons the debt list names and measures. The hammer arrives far more gently than a real one, because its fall is timed rather than sprung. And real alarm wristwatches are loud for a reason this model does not yet carry: the gong\'s foot drives the case back, and the case back is a diaphragm the size of a coin. Every part of that path is drawn — foot, plate, pillars, the screws that clamp the movement into the case — but nothing in the simulation yet lets sound travel along it.']: 'Ehrlichkeitsvermerk. Diese Zahl ist der Draht, der allein abstrahlt, und sie ist eine Untergrenze statt einer Vorhersage für die Uhr — aus zwei Gründen, die die Schuldenliste benennt und misst. Der Hammer trifft weit sanfter auf als ein echter, weil sein Fall getaktet statt gefedert ist. Und echte Weckerarmbanduhren sind aus einem Grund laut, den dieses Modell noch nicht trägt: der Fuß der Tonfeder treibt den Gehäuseboden an, und der Gehäuseboden ist eine Membran von der Größe einer Münze. Jedes Teil dieses Weges ist gezeichnet — Fuß, Platine, Pfeiler, die Schrauben, die das Werk ins Gehäuse klemmen —, aber noch lässt nichts in der Simulation den Klang diesen Weg entlanglaufen.',
  ['The gap between those words is where simulations usually lie, and this one keeps a public ledger of exactly that gap. The hands are simulated — their angles arrive through tooth counts, never assigned. The arming run is simulated — measured contact by contact. The hairspring\'s stiffness is modelled honestly enough that the beat follows from it as arithmetic, and the alarm\'s ringing tempo — for a long time the ledger\'s standing example of a merely authored number — is now derived the same way, from its own spring through a governor. The ledger did not empty and it did not move: the hammer\'s fall is still timed rather than sprung, and the gong\'s ring reaches the air straight off the wire and never through the case, which is where a real alarm gets most of its loudness. What changed is that both are now written down as decibels — about twenty-six for the spring and thirty for the case — instead of as notes, which is a debt list doing its job rather than an animation implying otherwise.']: 'In der Lücke zwischen diesen Wörtern lügen Simulationen gewöhnlich, und diese führt eine öffentliche Bilanz genau dieser Lücke. Die Zeiger sind simuliert — ihre Winkel kommen über Zähnezahlen an, nie zugewiesen. Der Spannlauf ist simuliert — Kontakt für Kontakt gemessen. Die Steifigkeit der Spirale ist ehrlich genug modelliert, dass der Takt daraus als Arithmetik folgt, und das Läutetempo des Weckers — lange das stehende Beispiel der Bilanz für eine bloß gesetzte Zahl — ist jetzt auf dieselbe Weise abgeleitet, aus seiner eigenen Feder über einen Regler. Die Bilanz leerte sich nicht und bewegte sich nicht: der Fall des Hammers ist weiterhin getaktet statt gefedert, und der Klang der Tonfeder erreicht die Luft direkt vom Draht und nie über das Gehäuse, woher ein echter Wecker den größten Teil seiner Lautstärke bekommt. Was sich änderte: beide sind jetzt als Dezibel aufgeschrieben — etwa sechsundzwanzig für die Feder und dreißig für das Gehäuse — statt als Vermerke, und das ist eine Schuldenliste, die ihre Arbeit tut, statt einer Animation, die etwas anderes nahelegt.',
};
