// GENERATED by tools/validated-configs.mjs --write — never edit by hand.
//
// TODO 158 — the configuration keys (src/layout.js configKey) the inspector
// battery has swept. The page marks any build whose key is not listed as an
// UNVERIFIED configuration; the battery re-verifies every row each run and
// fails on a stale one. Adding a row is a claim that a sweep covered it.
export const VALIDATED_CONFIGS = Object.freeze([
  Object.freeze({ point: "identity", key: "cfg1:{\"spec\":{\"reserveHours\":30,\"vph\":18000},\"route\":null,\"tuned\":[]}", evidence: "battery: full sweep of the default build" }),
]);
